### ISSUE TITLE
minor bug in smcp feature

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-sans-pro#102]
This (https://github.com/adobe-fonts/source-sans-pro/blob/master/Roman/family.fea#L621) line
`	sub [i.trk germandbls iogonek.d] by [Idotaccent.sc Germandbls.sc Iogonek.sc];`
needs to become
`	sub [i.trk germandbls iogonek.d] by [Idotaccent.sc germandbls.sc Iogonek.sc];`

InDesign still does the right thing, but not all editors might.

**Comment by erniemarch** [comment]
Checked in Roman version 2.034. This is corrected in the source feature file.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
