### ISSUE TITLE
Support for modern form of Bulgarian Cyrillic by .loclBGR

### ISSUE THREAD

**Issue by StefanPeev** [adobe-fonts/source-sans-pro#104]
I would like to collaborate by adding .loclBGR to locate the modern form of Bulgarian Cyrillic alphabet in Source Sans Pro. Is it of interest for the project?

**Comment by pauldhunt** [comment]
Thanks Stefan. What is your experience with font development? Have you previously drawn type? Are you able to submit work in UFO format?

**Comment by StefanPeev** [comment]
Thanks for the reply. I have more than 10 years experience in editing and making fonts. Here are mentioned some of them: http://luc.devroye.org/fonts-77041.html. One of my last projects is the Cyrillic Script to Alfredo Marco Pradil's font HK Grotesk: https://www.behance.net/gallery/28749913/HK-Grotesk-Open-Source-Typeface. HK Grotesk was nominated in a Bulgarian font competition - november this year, together with my own project for a font under the name of Malamir (still in a process).

**Comment by StefanPeev** [comment]
According to Botio Nikoltchev (lettersoup) issue: http://www.lettersoup.de/what-shall-be-done-for-bulgarian-cyrillic-loclbgr/ the following characters list is all which have to be included for loclBGR:

<img width="1187" alt="bildschirmfoto-2016-07-07-um-12 59 31" src="https://cloud.githubusercontent.com/assets/12949369/21070283/71a9288a-be8b-11e6-9233-e0eae95cc8b9.png">

The red characters in the pictures are in Russian style and the green ones in Bulgarian.

Д (uni0414) is optional
Ѝ (uni040D)
Л (uni041B)
Ф (uni0424) is optional
в (uni0432)
г (uni0433)
д (uni0434)
ж (uni0436)
з (uni0437)
и (uni0438) usually there is no need to redesign in Italic
й (uni0439) usually there is no need to redesign in Italic
ѝ (uni045D) usually there is no need to redesign in Italic
к (uni043A)
л (uni043B)
п (uni043F) usually there is no need to redesign in Italic
т (uni0442) usually there is no need to redesign in Italic
ц (uni0446)
ш (uni0448) usually there is no need to redesign in Italic
щ (uni0449) usually there is no need to redesign in Italic
ю (uni044E)

In my opinion we need also

ъ (uni044A)
ы (uni044B)
ь (uni044C)

And if the font implements small capitals Cyrillic (as is in SourceSansPro-Regular) we need corresponding Bulgarian Cyrillic small capitals letter (not included in next attachment).

Here is attachment of SourceSansPro-Regular as UFO with my offer for loclBGR glyphs. Please check them. UFO format is exported with TruFont.
[SourceSansPro-Regular.ufo3.zip](https://github.com/adobe-fonts/source-sans-pro/files/643510/SourceSansPro-Regular.ufo3.zip)

**Comment by pauldhunt** [comment]
@StefanPeev what UFO editing software are you using? is it possible to save in a format besides UFO3?

**Comment by moyogo** [comment]
You can use `python -c 'from defcon import Font; import sys; Font(sys.argv[-2]).save(sys.argv[-1], formatVersion=2)' SourceSansPro-Regular.ufo3 SourceSansPro-Regular.ufo` to convert from UFO3 to UFO2.

**Comment by StefanPeev** [comment]
@pauldhunt I used in this case FontForge to make UFO files.
[SourceSansPro-Regular.ufo.zip](https://github.com/adobe-fonts/source-sans-pro/files/738919/SourceSansPro-Regular.ufo.zip)

**Comment by pauldhunt** [comment]
@StefanPeev thank you. Do you intend to add these to the Light and Heavy masters?

**Comment by StefanPeev** [comment]
If you approve my work I will do the same in  the other styles also.

**Comment by StefanPeev** [comment]
@pauldhunt Here is a picture of SourceSansPro-Black as UFO with my offer for loclBGR glyphs. I'll mention that the drawing of some loclBGR glyph still need to be precized (for example the form of uni0432.loclBGR (small Cyrillic 've').

![sourcesanspro-black_01](https://cloud.githubusercontent.com/assets/12949369/22575507/92cbb3a8-e9be-11e6-947b-a5115d699190.jpg)

**Comment by pauldhunt** [comment]
@StefanPeev If you submit your work on Bulgarian Cyrillic, I will likely use this as the basis for further refinement when I get back to this project. Your work will make the process of developing final artwork much speedier. 😄

**Comment by StefanPeev** [comment]
@pauldhunt Thank you! I'll do it. I've submitted a PR here: https://github.com/adobe-fonts/source-sans-pro/pull/107 with the UFO files. But.. a lot of work need to be done for refining the drawings – I know it :)

**Comment by miguelsousa** [comment]
@pauldhunt Stefan submitted the glyphs in PR #137 and the changes are available for review in the branch named `bulg-cyr`.

**Comment by erniemarch** [comment]
confirm support for these in 3.006
