### ISSUE TITLE
Missing some characters for Adobe Charset support

### ISSUE THREAD

**Issue by pauldhunt** [adobe-fonts/source-sans-pro#106]
1 character(s) missing to support Adobe Latin 4:
        ‐  U+2010  HYPHEN

2 character(s) missing to support Adobe Greek 2:
        ̓  U+0343  COMBINING GREEK KORONIS
        ̈́  U+0344  COMBINING GREEK DIALYTIKA TONOS

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
