### ISSUE TITLE
Feature Request: True Small Caps

### ISSUE THREAD

**Issue by jrmiller82** [adobe-fonts/source-sans-pro#108]
True Small caps in several different weights with appropriate letter-spacing would be a fantastic addition.

**Comment by miguelsousa** [comment]
@jrmiller82 The roman fonts have had true small caps since version 1.038, [which was released in October 2012](https://github.com/adobe-fonts/source-sans-pro/releases/tag/1.038R). Are you perhaps using an older version?

**Comment by jrmiller82** [comment]
How do I access them? I just downloaded the latest release off of github yesterday. Do I need to pull from master instead?

**Comment by frankrolf** [comment]
Assuming you use software which supports the Small Cap OpenType features, here is a good description: https://www.typotheque.com/fonts/small_caps_in_opentype

On the web, you’d use `font-feature-settings: "smcp";` in your CSS.

**Comment by jrmiller82** [comment]
Why won't font developers release the small caps as separate fonts now a days? Many (most) programs can't handle those opentype features...

**Comment by fitojb** [comment]
That was true 20 years ago…

**Comment by jrmiller82** [comment]
Not necessarily. Word can't handle it. Libreoffice 5.3 just got rudimentary support and you have to type code into use it. Abiword can't. Which is why serious font faces come with small caps as separate fonts instead of relying on open type or other features.

**Comment by frankrolf** [comment]
Small Caps fonts are a thing of the past, @fitojb is right. There are many issues with dedicated fonts for typographic features, consistency and lack of cross-font kerning are two of them.
MS Word is not a good benchmark for font performance, out of the box it doesn’t even support kerning. 
OpenType features are important and software today should be expected to support them. In Western fonts, they may be perceived as non-essential, but after all, the world is not just Western.

_Serious Font Faces_: 
None of Adobe’s typefaces have been released with sidecar Small Cap fonts, and many of them support them. If it really irks you that much, you are welcome to fork the project and build your own Small Caps fonts.

**Comment by jrmiller82** [comment]
What irks me is why not both then? If I knew how to fork and build them I would. 

Unfortunately, some of us are stuck using certain software. I can't use LaTeX or XeTeX everywhere; and sometimes I have to use Word. It'd be nice to be able to use the Adobe source fonts with small caps with it.

**Comment by moyogo** [comment]
@jrmiller82 you can use pyftfeatfreeze (https://github.com/twardoch/fonttools-utils/) to make a small caps version of a font that has OpenType small caps.

**Comment by miguelsousa** [comment]
@jrmiller82 Source Sans Pro and all our other Source projects **ARE** "serious font faces", and we don't want to maintain multiple variants of the fonts just to address the shortcomings of applications. 

If you really care that much about small caps you should follow @moyogo suggestion, use applications that support OpenType's `smcp` and `c2sc` features, or log feature request issues against the apps you use.
