### ISSUE TITLE
Missing Trade Mark Sign? U+2122 

### ISSUE THREAD

**Issue by Shentao83** [adobe-fonts/source-sans-pro#110]
Hi there, when I integrate Source Sans Pro through Google Fonts, everything is working fine but the Trademark-Character: ™

It is being displayed with serif (looks like Times New Roman or something). If I add a fallback like this _font-family:"Source Sans Pro", Arial;_ then the ™ falls back to Arial. 

I use this to import the font (only bold, but with 400 added, the ™ doesn't work, too)
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:700);

If I try the preview here at Typecast http://typecast.com/preview/google/Source%20Sans%20Pro, the ™-Character does not work, too :-(

![image](https://cloud.githubusercontent.com/assets/4661712/24144234/cee14bc2-0e2c-11e7-8bec-37b3e24bc97c.png)

**Comment by codeman38** [comment]
This is a bug in Google Fonts' subsetting, and affects more than just Source Sans: google/fonts#78

**Comment by Shentao83** [comment]
Oh okay. I didn't know that. Sorry!
