### ISSUE TITLE
Request for special letter 'g' (nine-form, instead of eight-form)

### ISSUE THREAD

**Issue by KHoogteyling** [adobe-fonts/source-sans-pro#112]
Dear Adobe,

Subject: font Source Sans Pro

I have a question:
How can I / Can I generate / or adapt (the whole font, all weights) for showing the ‘alternative’ letter ‘g’ ('nine-form') instead of ‘primary choice/out of the box' for g (in 'eight-form')?

The font will be used in web and print, and is 'Source Sans Pro’ by Adobe, available through GoogleFonts, FontSquirrel.

Hope te hear from you, kind regards Karel Hoogteyling
(Sorry if I placed this request under issues wrongly, can not post it elsewhere)
![schermafbeelding 2017-05-05 om 09 18 22](https://cloud.githubusercontent.com/assets/28309797/25736736/1247e744-3174-11e7-8f8a-abe5ec0669ef.jpg)

**Comment by frankrolf** [comment]
Dear Karel Hoogteyling,

Similar previous requests have been addressed using https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze 
That tool was made exactly for scenarios like the one you describe.

**Comment by erniemarch** [comment]
Karel could also just apply ss03, assuming an OTF-feature aware app.  I guess outside of that, though…….


Ernest March • Quality Engineer, Type • Adobe • 408-536-4086
