### ISSUE TITLE
SourceSansPro-Black.otf "U+00A4 CURRENCY SIGN" wonky

### ISSUE THREAD

**Issue by nigeltao** [adobe-fonts/source-sans-pro#114]
SourceSansPro-Black.otf's "¤" glyph, aka U+00A4 CURRENCY SIGN, is wonky and asymmetric. The ttx dump of the Type 2 Charstring is:

```
<CharString name="currency">
-45 147 99 168 98 hstem
44 152 148 152 vstem
102 76 rmoveto
71 71 rlineto
31 -13 33 -6 33 32 34 6 31 hflex1
71 -71 85 85 -61 60 rlineto
21 30 13 36 43 vvcurveto
42 -12 36 -21 29 vhcurveto
60 60 -85 85 -70 -70 rlineto
-31 13 -34 7 -33 -33 -34 -7 -31 hflex1
-70 70 -85 -85 59 -60 rlineto
-20 -29 -12 -36 -42 vvcurveto
-43 12 -36 21 -30 vhcurveto
-60 -60 rlineto
253 85 rmoveto
-42 -32 32 52 52 32 32 42 42 32 -32 -52 -52 -32 -32 -42 hvcurveto
endchar
</CharString>
```

In particular, should the -13 in the first hflex1 line (and the corresponding +13 in the second) be zero?? That value (dy1) is the net change in y for the hflex1, since dy2 (-6) and  dy5 (+6) cancel each other out.

```
31 -13 33 -6 33 32 34 6 31 hflex1
```

The hflex1 op is specified in http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5177.Type2.pdf page 19.

This bug is about the OTF version. The TTF version doesn't look wonky.

OTF is "Version 2.020;PS 2.0;hotconv 1.0.86;makeotf.lib2.5.63406", as downloaded from https://github.com/adobe-fonts/source-sans-pro/releases/latest which redirected to https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.020R-ro/1.075R-it

AFAICT, no other glyph in the Source Sans Pro OTF set uses a flex operator (e.g. flex, flex1, hflex, hflex1).

**Comment by frankrolf** [comment]
Would you be able to provide a screenshot as well? That would be great!

**Comment by nigeltao** [comment]
Ah, on closer inspection, I've misread the 5177.Type2.pdf spec. (I'm writing my own rasterizer). The spec doesn't list a dy6 value for hflex1, so I assumed that it was zero. Instead, the value is implicitly whatever makes dy1 + dy2 + dy5 + implicit_dy6 equal zero.

Sorry for the noise.
