### ISSUE TITLE
The space and nbspace have different widths

### ISSUE THREAD

**Issue by khaledhosny** [adobe-fonts/source-sans-pro#115]
The space and nbspace glyphs in some of the fonts have different widths, is this intentional? If not I can send a PR making all nbspace glyphs have the same width as corresponding space glyphs.

**Comment by miguelsousa** [comment]
Same as #96

**Comment by khaledhosny** [comment]
LOL, I was pretty sure I reported this before but when I searched the issues nothing showed up.
