### ISSUE TITLE
Add Irish dotted consonants

### ISSUE THREAD

**Issue by twse** [adobe-fonts/source-sans-pro#117]
The font family as well as the Source Code Pro fonts support Irish but it only contains dotted cgms. (Anonymous Pro has all the dotted consonants for Irish.)

The dotted bdfpt should be added in the next update for support with the Latin-8 encoding.

See the image, the top paragraph is set in Calibri which contains all the dotted consonants, the bottom paragraph is set in Source Sans Pro which has some dotted consonants.

![irish language example](https://user-images.githubusercontent.com/2715694/29210487-cb75444e-7ece-11e7-842f-5bfd435695f2.png)

Credits for the text goes to Ciarán Ó Duibhín.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
