### ISSUE TITLE
Update copyright string to include current year

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-sans-pro#119]
https://github.com/adobe-fonts/source-sans-pro/blob/ff3bdec0a9ed367bfd6b05572f5dabebf030e7bb/familynameIDs.fea#L1

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084. Updated now.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
