### ISSUE TITLE
Can't install the release ttf files on OSX Sierra

### ISSUE THREAD

**Issue by wkoszek** [adobe-fonts/source-sans-pro#120]
My understanding is that the release version of TTF files should be ready to use and install on OSX via FontBook. However from what I see on my MBA laptop with OSX Sierra, that doesn't happen. I've done:

```
git clone https://github.com/adobe-fonts/source-sans-pro.git
cd source-sans-pro
mv Italic/Instances/BlackIt/font.ttf                    Italic_Instances_BlackIt_font.ttf
mv Italic/Instances/BoldIt/font.ttf                     Italic_Instances_BoldIt_font.ttf
mv Italic/Instances/ExtraLightIt/font.ttf               Italic_Instances_ExtraLightIt_font.ttf
mv Italic/Instances/It/font.ttf                         Italic_Instances_It_font.ttf
mv Italic/Instances/LightIt/font.ttf                    Italic_Instances_LightIt_font.ttf
mv Italic/Instances/SemiboldIt/font.ttf                 Italic_Instances_SemiboldIt_font.ttf
mv Roman/Instances/Black/font.ttf                       Roman_Instances_Black_font.ttf
mv Roman/Instances/Bold/font.ttf                        Roman_Instances_Bold_font.ttf
mv Roman/Instances/ExtraLight/font.ttf                  Roman_Instances_ExtraLight_font.ttf
mv Roman/Instances/Light/font.ttf                       Roman_Instances_Light_font.ttf
mv Roman/Instances/Regular/font.ttf                     Roman_Instances_Regular_font.ttf
mv Roman/Instances/Semibold/font.ttf                    Roman_Instances_Semibold_font.ttf
mkdir t
cd t
open .
```

I select all, and click "Open". I'm getting:

![screen shot 2017-09-18 at 10 51 35 pm](https://user-images.githubusercontent.com/483344/30577579-0d1f21d6-9cc4-11e7-9a5d-ee95ec55f3fd.png)

I tried inspecting the provided `ttf` files from FontBook:

![screen shot 2017-09-18 at 10 51 40 pm](https://user-images.githubusercontent.com/483344/30577592-235fb14a-9cc4-11e7-9acf-eda304fc68b3.png)

Is this meant to just work? I get the same result with released ttf files from `tar.gz` Any hints ? Typically it just works.

**Comment by miguelsousa** [comment]
Read the README.md. The `font.ttf` files are NOT the release version of the fonts.

**Comment by wkoszek** [comment]
@miguelsousa Using the `SourceSansVariable-Italic.ttf` file from the GitHub release gives me the same result on my system: can't install the font. That's why I'm a little puzzled.

**Comment by codeman38** [comment]
The "latest release" link in README.md now points to the `variable-fonts` tag, rather than the last 'normal' release tag. Not sure if the best solution to this would be to update the README to hard-code the specific release, or to make a new tag on the `release` branch, or what.
