### ISSUE TITLE
"Latest release" link in README points to variable-fonts

### ISSUE THREAD

**Issue by codeman38** [adobe-fonts/source-sans-pro#121]
It's currently more challenging than it should be to find a usable release of Source Sans Pro using the links in README.md. Rather than pointing to a release that's usable on most OSes, the "latest release" link in the README (https://github.com/adobe-fonts/source-sans-pro/releases/latest) currently points to the `variable-fonts` tag.

(This also applies to Source Code Pro and Source Serif Pro, incidentally.)

**Comment by miguelsousa** [comment]
The two links in the README.md file are all what's needed, and the notes on each release provide enough information. Variable and non-variable fonts will likely be part of the same release next time the project is updated. If you don't want the latest release just use the second link to browse all the releases. 
https://github.com/adobe-fonts/source-sans-pro/releases
