### ISSUE TITLE
Italic interrobang

### ISSUE THREAD

**Issue by AndrewKvalheim** [adobe-fonts/source-sans-pro#122]
Just a small enhancement request—We already have a [roman][roman-interrobang] interrobang (`‽`) but I'd find it useful to have an italic one as well.

[roman-interrobang]: https://github.com/adobe-fonts/source-sans-pro/blob/ff3bdec0a9ed367bfd6b05572f5dabebf030e7bb/Roman/Instances/Regular/font.ufo/glyphs/interrobang.glif

**Comment by pauldhunt** [comment]
I hope to spend some time brining the Italic up to the same level of character support as the upright fonts within the next year.

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084. These are now present.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.

**Comment by AndrewKvalheim** [comment]
Thanks!
