### ISSUE TITLE
Tiny nit: Use https in Github description

### ISSUE THREAD

**Issue by chazeah** [adobe-fonts/source-sans-pro#124]
Ahoy! Love the font family. One small thing I'd suggest...

In your Github product link, you use the `http://` URL:
![image](https://user-images.githubusercontent.com/899450/31800530-12b08536-b574-11e7-993c-c9ad37688e83.png)

Github offers HTTPS on all `github.io` pages – that means you could just as easily link here:
https://adobe-fonts.github.io/source-sans-pro/

Thanks!

**Comment by frankrolf** [comment]
Thanks!
