### ISSUE TITLE
U+203F UNDERTIE ‿ is a spacing character

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-sans-pro#125]
Some reference fonts:
<img width="478" alt="screen shot 2017-10-22 at 13 33 38" src="https://user-images.githubusercontent.com/2049645/31866032-a82645a0-b72d-11e7-908f-1e8f417b0932.png">

Source Sans Pro:
<img width="512" alt="screen shot 2017-10-22 at 13 33 45" src="https://user-images.githubusercontent.com/2049645/31866036-b2490306-b72d-11e7-82c3-13650a930c8e.png">

Wikipedia:
https://en.wikipedia.org/wiki/Tie_(typography)#Undertie

**Comment by pauldhunt** [comment]
@frankrolf cute smilies, bro. n‿n

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084. These is now a spacing character.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
