### ISSUE TITLE
Word spacing seems a bit too tight

### ISSUE THREAD

**Issue by kevinSuttle** [adobe-fonts/source-sans-pro#13]
Whenever I look at a sentence sent in SSP, I feel like I need to go in and manually set the word spacing. It's almost as if it's not using a full em space between words. It's very subtle (ha ha), but just that extra 1/3 of a space or so would make a big difference in readability.

**Comment by Lululalu** [comment]
@pauldhunt  After long reading sessions with many fonts, on my Kindle, I have felt that the word spacing in Source Sans 3 is a little to tight indeed, and it affects readability negatively, specially regarding smaller text.
