### ISSUE TITLE
ʤ proportion problem

### ISSUE THREAD

**Issue by ibrshv** [adobe-fonts/source-sans-pro#133]
"ʤ" symbol has a much larger "d" then normal font "d".
![image](https://user-images.githubusercontent.com/25700623/34992363-0a443b0e-fade-11e7-8b10-a26a430633ad.png)
ʤim dʒim
![image](https://user-images.githubusercontent.com/25700623/34992906-bf33551c-fadf-11e7-944c-29d9438d526f.png)
Ubuntu 16.04

**Comment by frankrolf** [comment]
The character ʤ is not contained in the typeface. What you are seeing is a fallback font.
