### ISSUE TITLE
missing package.json

### ISSUE THREAD

**Issue by keradus** [adobe-fonts/source-sans-pro#135]
Hi,
could you please create `package.json` and register project at `npm` registry?
It would ease everyone installing the package.

Yes, I do know that one could install npm dependency directly from github, yet:
- it's slower, as...
- it's running `git clone` under the hood, so...
- if one wants to run node project in docker container, his container now... has to have `git` build-in, to be able to install `source-sans-pro` dependency.

**Comment by miguelsousa** [comment]
Please submit a PR with `package.json` for us to have a better idea of what's needed.

**Comment by keradus** [comment]
https://github.com/adobe-fonts/source-sans-pro/commit/472ed41800c6def702c002c20d200da42cc699d8

**Comment by miguelsousa** [comment]
@keradus is this what you're looking for? https://www.npmjs.com/package/npm-font-source-sans-pro

**Comment by keradus** [comment]
no, I'm not looking for private fork of one guy that was last modified 2 years ago and doesn't have any newesr font files.
I'm looking for official support of **this** lib for npm

**Comment by miguelsousa** [comment]
He has the latest. The only newer files we made are variable fonts.

**Comment by keradus** [comment]
exactly

**Comment by miguelsousa** [comment]
I've updated the `package.json` file in the **release** branch and published it to https://www.npmjs.com/package/source-sans-pro
Let me know how that works.

**Comment by keradus** [comment]
Just checked it.
Works like a charm, thanks !
Big thanks ;)
