### ISSUE TITLE
Hi, Georgian type designers have finished and included Georgian glyphs to your font. Do you want to update your font?

### ISSUE THREAD

**Issue by gusbemacbe** [adobe-fonts/source-sans-pro#138]
Hello,

Some months ago, I contacted Georgian type designers, they worked with and finished one of fonts – Source Sans Pro Regular.

Do you want to update your font? I do not know if they have Github accounts.

But you can check their topic, sorry that their topic is in Georgian, but Akaki and Besarion speak English. You should contact Akaki and Besarion. 

https://www.facebook.com/groups/geotypography/permalink/1142977455836430/

As this version is finished, I am going to build other weights. 

Gustavo

**Comment by frankrolf** [comment]
You have seen this, right? https://github.com/adobe-fonts/source-sans-pro/pull/129

**Comment by gusbemacbe** [comment]
Ah, @frankrolf! But In that discussion, that version is outdated 18 days old, you have to get a newest version which was updated 5 days ago.
