### ISSUE TITLE
Lookup order bug when using {smcp} and {frac}

### ISSUE THREAD

**Issue by RoelN** [adobe-fonts/source-sans-pro#139]
"1/2 beers" will not turn into "½ BEERS", but "1/2 BEERS" when applying both {smcp} and {frac}. For other fonts, this does work, and individually applied they work for `SourceSansVariable-Roman.ttf` — but not together. When researching this it was pointed out to me that this is most likely a bug in the lookup order.

**Comment by pauldhunt** [comment]
thanks for reporting, will correct in next revision.

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084 in InDesign CC 2018, Illustrator CC 2018, Photoshop CC 2018. Seems to work correctly in all three, so calling this fixed.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
