### ISSUE TITLE
Request to include two- and three-em dash

### ISSUE THREAD

**Issue by funkyfuture** [adobe-fonts/source-sans-pro#141]
these glyphs are useful to imply missing data in a field, especially when single mdashs are used for other purposed in the context.

- TWO-EM DASH / U+2E3A / `⸺`
- THREE-EM DASH / U+2E3B / `⸻`

they really make an impression.

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084. These are now present.

**Comment by miguelsousa** [comment]
@pauldhunt It'd be better to close when the new version gets released

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
