### ISSUE TITLE
Unable to print OTF on Windows 10

### ISSUE THREAD

**Issue by bencgreen** [adobe-fonts/source-sans-pro#142]
I've had the OTF fonts installed on Windows 10 for a long time, and love it!

However, today both Windows and Office updated, and one of them seems to have broken my ability to print documents using Source Sans Pro.  In the Event Viewer, the file is spooled and immediately deleted - no error message, nothing.

Changing to a different font, or installing the TTF font, makes the document print.

I've tried reinstalling the font, the printer driver - even reinstalling Office, but to no avail.  A couple of times when installing the OTF, Windows refuses to install the Regular font - it simply says 'it appears to be an invalid font'.  That's no good as the Regular is the most-used version!

I will use the TTF font for now, which looks the same when printed, but the OTF looks sooo much better on-screen, I'd really like to be able to continue using it if possible.

Any ideas?

**Comment by miguelsousa** [comment]
@bencgreen do you have any other OTF fonts installed? Do they exhibit the same problem?

**Comment by miguelsousa** [comment]
@bencgreen tell us the versions of the apps and of the system you have, so we can try to reproduce it. If you can provide the steps to reproduce it, it'd be even better.

**Comment by bencgreen** [comment]
Thanks for getting back to me.

Windows 10 Pro 1803 Build 17134.48
Office 365 1805 Build 9330.2014

The only steps to reproduce are - create a new document, select Source Sans Pro, type something, try to print - nothing.

But it gets curiouser and curiouser - I've tried a couple more OTF fonts and it seems they don't print either - or rather, they won't print to my HP (laser) printer, but they will print to PDFCreator, and to my Canon (inkjet) printer.  I've tried WordPad as well, and the same thing happens.  I have also opened an OTF font file, and I can't print it from there either.

The frustrating thing is that on Wednesday it did all print - before the latest Windows build.

Is this a known problem?  I've reinstalled my HP printer driver at least three times - even using print management to completely remove previous versions of the driver.

I can't reproduce the 'this appears to be an invalid font' error that I was receiving yesterday - I had rebooted several times, but obviously something I did has fixed that particular problem.  So it looks like this isn't a SSP issue after all - sorry for posting!

**Comment by miguelsousa** [comment]
Thanks for bringing this issue to our attention. We were able to reproduce it, and are in discussions with Microsoft. What we know is that the problem was introduced in **Windows 10 1803 release**, affects all **OpenType-CFF (.otf)** fonts, and only happens with **Type 4** printer drivers. You can check the Driver Type of your printer by opening the *Print Management* panel.

**Comment by bencgreen** [comment]
Thanks - I managed to find a Type 3 driver for my printer, so I'm up and running again.  Is there an official bug report at MS that I can follow, to know when it's fixed?

**Comment by miguelsousa** [comment]
I don't know of any public-facing reference to the issue at the moment.

**Comment by bencgreen** [comment]
As an extra comment - it also happens with certain Type 3 drivers.  I have three drivers installed for my HP printer now - the Universal Printer Driver is Type 3 and it works, but the PCL 6 driver doesn't work, whether I choose the Type 3 or Type 4 version.

**Comment by huckleberrypie** [comment]
I am having an issue with this as well, apparently. I can print if the fonts are in TTF format, but not if they're OTF. Using an HP DeskJet 2135 with the latest available drivers.

**Comment by erniemarch** [comment]
This turns out to be an issue with Windows 10 Type 4 printer drivers and OTF fonts (all OTFs, not just Source Sans).  You can open the printer management console and check (Start\Run\printmanagement.msc) your driver type. Microsoft is aware of the issue and has created a fix which we have verified in the latest test builds of Windows 10. The bigger question is when that fix will actually get out in the field; they tend to release updates to users based on newer computers first, older ones later. The only immediate workarounds we know of are to either use the TTFs or try to find a Type 3 driver for your printer. A quick glance at HPs site doesn’t reveal the driver type so that might be difficult.

**Comment by huckleberrypie** [comment]
I am having an issue with this as well, apparently. I can print if the fonts are in TTF format, but not if they're OTF. Using an HP DeskJet 2135 with the latest available drivers.

**Comment by bencgreen** [comment]
@huckleberrypie yes my HP driver is Type 3 and is affected by this issue.

**Comment by huckleberrypie** [comment]
Installing KB4340917 either via Windows Update or Microsoft's update catalogue should fix the issue. ;)

**Comment by bencgreen** [comment]
Yup all fixed for me!

**Comment by paulpitchford** [comment]
I'm experiencing this in Win 10 Pro 19041.264 with a Type 4 driver. Has this reared it's head again?

**Comment by erniemarch** [comment]
Paul,  I am unable to reproduce this. Using the version of Windows you list. We are out of the office and my access to physical Type 4 printer is blocked. I used both the XPS printer and MS PDF printer which are both listed as Type 4 drivers, but output was correct.

**Comment by paulpitchford** [comment]
Ok, here are a few more details.

1. Created a blank document and printed a test page using Calibri just fine.
2. Changed the font to the "Dax" OTF font and the page spools but doesn't print. 

It doesn't seem to spool to the full size of the document. (make sense?) It'll spool to say 75% of the kb's being spooled then disappears out of the print window.

**O/S, Office, Drivers:**
Windows 10 19041.26
Office 365 Build 12730.20270 Click to Run
Kyocera ECOSYS M5521cdn v4 (XPS) 5.1.1708.0 Type 4

If I use the universal Type 3 driver it will also print. I can't use that in this instance as the driver is really poor and missing a lot of features I'd use. Fortunately in my situation, there is a TTF version of the font that looks ok but I didn't find the font until after I read this thread but thought it may be of use to someone else.
