### ISSUE TITLE
Cramped & Squashed

### ISSUE THREAD

**Issue by anyotherway** [adobe-fonts/source-sans-pro#143]
Source Sans Pro is cramped like sardines in a can, UGLY! Sisters Source Serif Pro and Source Code Pro demonstrate excellent glyph and line spacing. SOMEONE PLEASE SPACE SOURCE SANS PRO TO MATCH SOURCE CODE PRO AND SOURCE SERIF PRO.

**Comment by frankrolf** [comment]
You need to back up such statements with specifics, e.g. screenshots and usage scenarios.

**Comment by miguelsousa** [comment]
This must be spam
