### ISSUE TITLE
Incorrect style names in OS X applications using variable fonts

### ISSUE THREAD

**Issue by m4rc1e** [adobe-fonts/source-sans-pro#144]
For https://github.com/adobe-fonts/source-sans-pro/releases/tag/variable-fonts on OS X 10.12.4

If we load the Variable font in Font Book v7 (302.1) we get the following:

![screen shot 2018-05-29 at 14 39 29](https://user-images.githubusercontent.com/7525512/40662389-1c768e20-634e-11e8-8857-7d2260616289.png)

Roman styles are not displayed correctly.

Same happens in Pages v7 (5576)

![screen shot 2018-05-29 at 14 42 43](https://user-images.githubusercontent.com/7525512/40662559-92818a5c-634e-11e8-828e-eac75432ba46.png)

atm, can't tell if this is a font issue or system. I assume that the Roman style names should be displayed in the same manner as the Italics.

**Comment by frankrolf** [comment]
I can’t reproduce this issue in Font Book Version 8.0 (314.1)
Judging the Pages dropdown, this seems partially related to the style linking across Romans and Italics. 
I have Pages version 7.0.1 (5579), and the dropdown looks slightly better (still not entirely correct):
<img width="277" alt="screen shot 2018-05-29 at 14 07 59" src="https://user-images.githubusercontent.com/2049645/40685759-0181a964-634a-11e8-9eb1-6c06f50c962d.png">

**Comment by m4rc1e** [comment]
Thanks for testing.

I'm currently working on a family which consists of two VF fonts, one for Italic, the other for Roman. I'll let you know if I get a better result.

**Comment by m4rc1e** [comment]
Just upgraded to High Seirra. Menus now match yours.

![screen shot 2018-06-20 at 14 17 21](https://user-images.githubusercontent.com/7525512/41660710-bf826d9e-7494-11e8-833f-e580e1b734bd.png)

Also In Pages, there's no difference when selecting ExtraLight and Light instances. Users will only get the Light.
