### ISSUE TITLE
Some greek lowercase do not change to small cap versions with smcp feature

### ISSUE THREAD

**Issue by erniemarch** [adobe-fonts/source-sans-pro#145]
alpha, beta, gamma, phi, and chi do not change to their small cap version like other greek lowercase when the smcp feature is applied. They are instead flagged as glyphs in the IPA range. Please check.

**Comment by pauldhunt** [comment]
@erniemarch This is as expected. If the language tagging is set to a Latin-based language (eg English), the characters listed are swapped to the Latin forms. To get proper handling for Greek, you will need to set your text tagging to Greek. Please test with proper tagging and report if you still find this to be an issue.

**Comment by miguelsousa** [comment]
@pauldhunt seems to me that there's either a feature-sorting issue, or the `smcp` feature is missing substitutions for the latinized lowercase Greek glyphs.

**Comment by miguelsousa** [comment]
Paul and I discussed this in depth and ultimately concluded that, given the current support for small caps in the font — which does not cover characters from the IPA blocks — it is working as designed. Support for small caps of IPA characters is expected to be added in the future.
