### ISSUE TITLE
Glyphs not reachable by feature

### ISSUE THREAD

**Issue by erniemarch** [adobe-fonts/source-sans-pro#147]
In the Romans:
21 unreachable glyph(s)
 uni03020300.c
 uni03020301.c
 uni03020303.c
 uni03020306.c
 uni03020309.c
 uni03060300.c
 uni03060301.c
 uni03060303.c
 uni03060309.c
 uni03080300.c
 uni03080300.g
 uni03080301.c
 uni03080304.c
 uni0308030C.c
 uni03120300
 uni03120301
 uni03120303
 uni03130300
 uni03130301
 uni03130303
 uni1FFD.cap

In the Italics:
26 unreachable glyph(s)
 uni0300.g
 uni0301.g
 uni03020300.c
 uni03020301.c
 uni03020303.c
 uni03020306.c
 uni03020309.c
 uni0306.K
 uni0306.k
 uni03060300.c
 uni03060301.c
 uni03060303.c
 uni03060309.c
 uni03080300.c
 uni03080300.g
 uni03080301.c
 uni03080304.c
 uni0308030C.c
 uni0312.g
 uni03120300
 uni03120301
 uni03120303
 uni0313.g
 uni03130300
 uni03130301
 uni03130303

**Comment by pauldhunt** [comment]
I've addressed this in the upcoming build, but some of these are likely bogus and are either not being counted due to what features they are included in or the fact that they are triggered contextually.

**Comment by miguelsousa** [comment]
@pauldhunt please provide a few examples of the items you think are bogus so I can investigate. Thanks.

**Comment by erniemarch** [comment]
checked in newest build (3.006). This has been fixed.
