### ISSUE TITLE
Convert UFOs to version 3

### ISSUE THREAD

**Issue by miguelsousa** [adobe-fonts/source-sans-pro#148]

**Comment by miguelsousa** [comment]
The [UFO instances are version 3 now](https://github.com/adobe-fonts/source-sans-pro/blob/master/Roman/Instances/Regular/font.ufo/metainfo.plist#L7-L8), after Source Sans' v3.006 release.
So the UFO's left to be converted are the masters.

**Comment by pauldhunt** [comment]
Fixed in [version 3.028](https://github.com/adobe-fonts/source-sans-pro/releases/tag/3.028R).
