### ISSUE TITLE
source-sans-pro.css removed

### ISSUE THREAD

**Issue by compeek** [adobe-fonts/source-sans-pro#152]
What was the reason for removing `source-sans-pro.css` as part of this commit? https://github.com/adobe-fonts/source-sans-pro/commit/9c934ce250b4987c43fd1ac8d066182cbf27e98c

I understand bower is a thing of the past, but our Angular project was relying on the CSS file, and our build suddenly broke today because the release branch no longer includes it.

Is the expectation that we would generate our own CSS file now?

Thank you!

**Comment by miguelsousa** [comment]
Hi Alex. Sorry for breaking your build. I had no way to know that the file was still being referenced. It has been restored. Thanks for reporting.

**Comment by miguelsousa** [comment]
I've also added `source-sans-variable.css` that references the variable fonts.

**Comment by compeek** [comment]
Excellent, thank you Miguel. We locked our dependency version now so any future changes won't affect us, but I do think the CSS file is useful here, so thank you for restoring it and updating it.
