### ISSUE TITLE
Add support for U+2326 ⌦

### ISSUE THREAD

**Issue by LilianValero** [adobe-fonts/source-sans-pro#153]
Hi, it seems that the delete MAC glyph is not rendered correctly in the v2.0.40. May you confirm, please?
With the v2.040, we have:
![delete_item](https://user-images.githubusercontent.com/4578106/48706546-e4efb200-ebfc-11e8-8ce4-50e7d39cf6db.png)
![delete_rule](https://user-images.githubusercontent.com/4578106/48706547-e5884880-ebfc-11e8-87b3-717118f8540e.png)
Basically, we should have:
![fixed_delete_item](https://user-images.githubusercontent.com/4578106/48706549-e5884880-ebfc-11e8-8cd5-658e7b500369.png)

**Comment by frankrolf** [comment]
I assume you are talking about ⌫ U+232B, and I don’t think this glyph has ever been supported in Source Sans Pro.
You can find fonts which support that glyph here: https://www.fileformat.info/info/unicode/char/232b/fontsupport.htm

**Comment by miguelsousa** [comment]
Related to #97
Support for ⌫ U+232B was added in v2.040, in the upright fonts at least. Is it not there?

**Comment by LilianValero** [comment]
Yes it seems that upleft MAC glyph is there but not the upright MAC glyph.

**Comment by LilianValero** [comment]
Do you think that we can add someday the upright, please?

**Comment by frankrolf** [comment]
Oof, I apologize. I wasn’t aware of the addition and looked at an outdated file.
However I can see the glyphs in the latest version of Source Sans Pro Regular:
<img width="988" alt="screen shot 2018-11-20 at 09 20 23" src="https://user-images.githubusercontent.com/2049645/48760209-93e7c880-eca5-11e8-99ee-75a3f573e0c5.png">

**Comment by LilianValero** [comment]
yes but not the upright which corresponds to the DEL command.

**Comment by LilianValero** [comment]
We'd like to use the upright:
<img width="39" alt="delete glyph" src="https://user-images.githubusercontent.com/4578106/48761472-01492880-eca9-11e8-9b06-bf836751dbc7.png">
for delete actions of our application.
It seems that the upright are used by other applications like IntelliJ to delete items.

**Comment by frankrolf** [comment]
It always is easier to communicate using code points upfront – if you mean U+2326 ⌦, then my original statement is true: This character has not been supported in Source Sans Pro.
It would be simple enough to add the glyph, however I’ll leave this decision to @pauldhunt.

FYI – upright does not mean right-pointing. Upright means “Roman, not Italic“.

**Comment by LilianValero** [comment]
Thks to investigate and sorry for the confusion.

**Comment by erniemarch** [comment]
confirmed in both roman and italic 3.006
