### ISSUE TITLE
Letters 'i' and 'j' miss dots in PDF exported from MS Word 2016 (2.040R-ro)

### ISSUE THREAD

**Issue by llvs** [adobe-fonts/source-sans-pro#154]
The title already tells the whole story:
Letters 'i' and 'j' miss dots in the resulting PDF which is exported from MS Word 2016 with the built-in save as functionality. 
- Downgrade to release 2.020 works
- Release 2.040 works using Adobe Acrobat PDF generation
Cheers,
llvs

**Comment by frankrolf** [comment]
Could you please attach such a PDF to this issue? Thank you.

**Comment by llvs** [comment]
I see just now that colons in the time column on the left hand are also missing.

[Agenda test nm.pdf](https://github.com/adobe-fonts/source-sans-pro/files/2596072/Agenda.test.nm.pdf)

**Comment by erniemarch** [comment]
I have tried unsuccessfully to reproduce this using both Mac and Win versions of Word 2016. Any additional information about setup might be useful.

**Comment by llvs** [comment]
We could reproduce it on two Windows 10 (v1803) machines before downgrading. Word and Windows both use latest patch levels. Other than that, I don't know what special item our setup might include.

**Comment by frankrolf** [comment]
Also here: OTF or TTF? 
@llvs Could you please try the opposite format of the one you’re using? It may be that Windows still is better with TTF in some cases.

**Comment by llvs** [comment]
I am quite sure, that we had the TTF installed, as we know that OTF often poses problems in Windows, especially with MS Office. If I find the time, I can try OTF, however I assume that it is not better than TTF.

**Comment by frankrolf** [comment]
All right, thanks! It’s tough on this end because QE couldn’t reproduce the problem at all. I do know however that Word’s built-in PDF tools may cause problems sometimes. See an example of that here:
https://answers.microsoft.com/en-us/msoffice/forum/all/missing-characters-when-you-save-as-pdf-an-ms-word/7711709c-32a2-4c27-b402-9db327598a4e

You may want to try using the Adobe PDF “printer”:
https://helpx.adobe.com/acrobat/using/print-to-pdf.html

**Comment by frankrolf** [comment]
Reproduced on this end. Step-by-step:
- install Source Sans Pro Regular 2.040 TTF
- create new Word document in MS Word 2016 on Windows 10.
- paste the text `9:15 Arbeiten Kic projekte`

## option 1
File → Save as… → PDF
result: colons, dots on `i` and `j` are missing
## option 2
File → Print → Microsoft Print to PDF
result: colons, dots on `i` and `j` are missing
## option 3
File → Save as Adobe PDF …
shows Adobe Sans fallback font

## workaround
All above options work properly when using the OTF font.

**Comment by llvs** [comment]
Thank you all for investigating and fixing this!

**Comment by miguelsousa** [comment]
Fixed fonts haven't been issued yet. Let's keep the issue open until then.

**Comment by miguelsousa** [comment]
Fixed in this release https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.045R-ro%2F1.095R-it
