### ISSUE TITLE
Glyph for U+0281 incorrect

### ISSUE THREAD

**Issue by AshtarBalynestjar** [adobe-fonts/source-sans-pro#155]
The IPA symbol for a voiced uvular fricative should be a small capital r reflected across a horizontal axis, not rotated 180°.

**Comment by erniemarch** [comment]
version 2.040 matches Unicode chart for this glyph. Do you have an older version of the font?

**Comment by AshtarBalynestjar** [comment]
Probably. I’m commenting on the version currently available on Google Docs, which may be outdated.

**Comment by miguelsousa** [comment]
Yeah, that's the old version.
