### ISSUE TITLE
Add some Pe̍h-ōe-jī diacritics

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-sans-pro#157]
[Pe̍h-ōe-jī](https://en.wikipedia.org/wiki/Pe%CC%8Dh-%C5%8De-j%C4%AB) is a romanization of Min Nan Chinese, which has some special diacritics not appearing in western texts. However both of them are missing in Source Sans Pro:
U+0358 COMBINING DOT ABOVE RIGHT
U+030D COMBINING VERTICAL LINE ABOVE

See my screenshot
![screenshot](https://user-images.githubusercontent.com/10364351/49956824-1149d600-fefe-11e8-89f3-1112d9332bf5.PNG)

**Comment by pauldhunt** [comment]
Will add in next release.

**Comment by erniemarch** [comment]
confirmed present in both roman and italic 3.006 build

**Comment by KrasnayaPloshchad** [comment]
🤝

**Comment by svenper** [comment]
How about Ṳ and ṳ (as single code points `U+1E72` and `U+1E73`)?

They are also used in other romanizations like Pha̍k-fa-sṳ, Pha̍k-oa-chhi, and Bàng-uâ-cê.
