### ISSUE TITLE
Add support for combining diaerasis below

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-sans-pro#158]
The usage of diaerasis below have been documented in the Dictionary of the Foochow dialect, which uses a [romanization](https://en.wikipedia.org/wiki/Foochow_Romanized) to transliterate Fozhou dialect of Eastern Min Chinese. However it doesn’t works well with Source Sans Pro.
![screenshot](https://user-images.githubusercontent.com/10364351/49957707-8dddb400-ff00-11e8-900a-f4d6a2a4195d.PNG)

**Comment by pauldhunt** [comment]
For the combining dieresis below to function with accented characters, the typesetting application must support contextual decomposition in order for proper mark positioning. So I would see this not as a font bug, but a flaw with your typesetting application.

**Comment by miguelsousa** [comment]
Per [Khaled's comment](https://github.com/harfbuzz/harfbuzz/issues/1559#issuecomment-457419195),
> Works with both `hb-view` and LibreOffice 6.1.4.2 on Linux with Source Sans Pro 2.045. Either a bug on your version of the fonts or LibreOffice.

The fonts bundled with the LibreOffice version you're using may be outdated.

**Comment by KrasnayaPloshchad** [comment]
Nice to see the bugfix in the latest release.
