### ISSUE TITLE
Add support for two IPA superscripts

### ISSUE THREAD

**Issue by AshtarBalynestjar** [adobe-fonts/source-sans-pro#160]
U+02B1 ʱ and U+02C0 ˀ represent breathy voice and glottalization, respectively. Note that although they don’t appear on the one-page IPA chart, they aren’t unofficial symbols; they have been used in official publications such as the Illustrations of Bengali ([here](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/93859C8D261F043FE7EEC6ACDA28C3B5/S0025100310000071a.pdf/bengali_bangladeshi_standard.pdf)) and Danish (not accessible for free) by the International Phonetic Association. I’d say that I’ve seen them used more often than some superscripts actually on the one-page chart, such as the ones for lateral and nasal release.

**Comment by pauldhunt** [comment]
Will add in next release.

**Comment by erniemarch** [comment]
confirm present in both roman and italic of 3.006 build
