### ISSUE TITLE
Windows Font Preview shows fallback for figures, punctuation for 2.040/1.090 TTFs

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-sans-pro#163]
This was previously submitted by email, but never made it onto GitHub.

NB: 
- this was confirmed on both Windows 7 and Windows 10
- the bug seems to affect only the display in the font preview application, not the performance of the font in an app such as WordPad (the figures work as expected)
- the font preview application shows OTF fonts just fine
![win7_black](https://user-images.githubusercontent.com/2049645/50687483-c1a08b00-1021-11e9-84f3-05667aac6194.png)
![win7_lightitalic](https://user-images.githubusercontent.com/2049645/50687484-c1a08b00-1021-11e9-9600-845ab4178a2f.png)
![win10_extralightitalic](https://user-images.githubusercontent.com/2049645/50687485-c1a08b00-1021-11e9-83f6-6fbc622d3473.png)
![win10_light](https://user-images.githubusercontent.com/2049645/50687486-c1a08b00-1021-11e9-94d4-73434ac568a1.png)

**Comment by miguelsousa** [comment]
Fixed in this release https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.045R-ro%2F1.095R-it
