### ISSUE TITLE
"ff" looks strange

### ISSUE THREAD

**Issue by anasbouzid** [adobe-fonts/source-sans-pro#165]
The second f in "office" looks different with the `regular` and `semibold` font. To reproduce the issue, go to [google font](https://fonts.google.com/specimen/Source+Sans+Pro) and type "ff" with a font-size of 24px. I've also downloaded the original font from the source code and was able to reproduce the issue with a different font-size on both chrome and firefox.

![source-sans-pro](https://user-images.githubusercontent.com/7522456/52834851-b5f1bb00-30db-11e9-9330-d2f360ca949a.png)

**Comment by frankrolf** [comment]
This seems to be a design feature:
<img width="1136" alt="Screen Shot 2019-03-21 at 20 40 27" src="https://user-images.githubusercontent.com/2049645/54783557-976e6a80-4c19-11e9-9654-4f9799a3f01e.png">

**Comment by anasbouzid** [comment]
yes it's a ligature, but if you look closely at my screenshot, the second "f" in the  `regular` and `semibold` font doesn't resemble the first one

**Comment by frankrolf** [comment]
Same in my screenshot – the first f is lower than the 2nd. It’s not as obvious in larger size, but it may be one of the things that gives Source Sans it’s flavor. An alternate explanation for the difference in rasterization could be the first f not touching an alignment zone.

**Comment by pauldhunt** [comment]
@anasbouzid can you check to see if this is still an issue with the latest fonts? if so, i’ll try to have a closer look at this in the next round of updates.

**Comment by anasbouzid** [comment]
@pauldhunt I've made a [little experiment](https://codepen.io/tntrazor/full/oNNvZbd) to test the latest font, I no longer can reproduce the issue in a high PPI screen, but it still remains on a low PPI screen
![source](https://user-images.githubusercontent.com/7522456/66142994-590d2b80-e5fe-11e9-9aba-0f46dcdce053.png)

The picture above shows the difference between the font-size in the same screen, with 26px the second f is a little bit taller, the f series is also inconsistent, with a font-size of 27px the font looks normal. Your mileage may vary, feel free to change the font-size.

**Comment by pauldhunt** [comment]
@anasbouzid I've attempted tweaking the hinting for this glyph. Can you check the latest versions to see if this is still an issue?
