### ISSUE TITLE
Rendering Weird

### ISSUE THREAD

**Issue by anthonycalixto** [adobe-fonts/source-sans-pro#17]
I am using this font hosted on Google web fonts and at first it was rendering fine but now it looks off. Something about it looks weird. It looks pixelated and it's annoying. I noticed it's looking weird on another site that's using the same font (screenshot below). What's the problem? There's nothing wrong with the CSS on the site I'm working on.

On the first screenshot, I am using the font on the header (with the orange background) and that's at a weight of 400. Something about it looks odd, it looked much better a few days ago.

![weird](https://f.cloud.github.com/assets/3173248/39667/ca2da19c-553b-11e2-809b-06e0fe71fc04.png)
![weird2](https://f.cloud.github.com/assets/3173248/39668/ccebb0b8-553b-11e2-8f5c-2b04fb736ae4.png)

**Comment by davelinke** [comment]
I was experiencing easing failures on Windows with the font. The EOT file i was using was a converted TTF file. I used the EOT files provided by Adobe at Github and now it looks all right. Although my case was not a failure of the adobe files themselves, i just wanted to post it here in case someone is experiencing this by not using the files available on Github.
