### ISSUE TITLE
TTF vs OTF rendering difference on Windows (darkness/boldness)

### ISSUE THREAD

**Issue by herrernst** [adobe-fonts/source-sans-pro#170]
Out of curiousity I've compared the OTF and TTF webfonts (WOFF). I've noticed that on Windows 7 or 10 (IE, Chrome, FF, all using DirectWrite IMHO), the OTF looks bolder/darker.

https://rawgit.com/herrernst/31b75f42bc12acc7c8be70de01ea237a/raw/4d3456711b90c107d9d52619b0bb0305440d905d/index.html

![Bildschirmfoto am 2019-06-11 um 16 41 57](https://user-images.githubusercontent.com/20795/59281974-75104a00-8c68-11e9-98ce-1a8178815426.png)

Does anybody know why this is happening? I've noticed the same behavior with another font, so it's probably not specific to this one. Thanks.

**Comment by frankrolf** [comment]
It’s a general difference – I think you’ll be able to observe rasterization differences in most fonts that come in both TTF and OTF flavors.
<img width="952" alt="Screen Shot 2019-06-11 at 10 56 17" src="https://user-images.githubusercontent.com/2049645/59282924-b1778200-8c37-11e9-91e5-3af7901a2cb8.png">
![Screen Shot 2019-06-11 at 10 56 11](https://user-images.githubusercontent.com/2049645/59282926-b1778200-8c37-11e9-9520-7665e76cae42.png)


It also depends on the OS, browser used, screen, and other factors.
Here are four screenshots from Safari and Chrome, on hi- vs lo-DPI screens.
<img width="952" alt="Screen Shot 2019-06-11 at 10 56 25" src="https://user-images.githubusercontent.com/2049645/59282921-b1778200-8c37-11e9-9b1f-3ba478f95ada.png">
![Screen Shot 2019-06-11 at 10 56 22](https://user-images.githubusercontent.com/2049645/59282923-b1778200-8c37-11e9-8afa-9e752aa42a5b.png)

**Comment by herrernst** [comment]
On your screenshots from macOS, I see no difference between OTF and TTF. I know font rendering is different between OSes and browsers and low/hi-DPI, but I'm surprised there's such a huge difference between OTF and TTF on the same platform.

**Comment by frankrolf** [comment]
OTF and TTF use different hinting methods, so some degree of visual difference is expected.
Note that you can also fine-tune the “darkness” of type on Windows, however I’m not sure how different font formats will be affected.
Probably you’re already aware of this site, which may help in understanding some of the differences:
http://rastertragedy.com/RTRCh0.htm

**Comment by herrernst** [comment]
Thanks for the link.
