### ISSUE TITLE
en/em dash do not extend to en/em width

### ISSUE THREAD

**Issue by madig** [adobe-fonts/source-sans-pro#172]
Just noticed that `endash` is 480 fU and `emdash` is 800 fU wide. Shouldn't they be 500 and 1000 fU wide, respectively? Is this a conscious design decision?

**Comment by RuixiZhang42** [comment]
I’d say that the majority of typefaces do not set their dashes at precisely half/full em units:

> ![dashes](https://user-images.githubusercontent.com/39968857/61303753-0cac0f80-a7b6-11e9-9d0a-c90f03813e52.png)

After all, one em no longer equals precisely the width of an uppercase M a long time ago.

**Comment by madig** [comment]
Mh, fair enough. Thanks for the list.
