### ISSUE TITLE
Cannot build from source (2.045ro/1.095it)

### ISSUE THREAD

**Issue by medicalwei** [adobe-fonts/source-sans-pro#173]
I am going to package Source Sans Pro to Debian (and subsequently Ubuntu), resolving issue #111.

However, as Debian needs fonts to be built from source code, I found a problem that your source code does not build.  I installed AFDKO 2.9.9a12 either from my current Debian packaging, or your recommended method on macOS 10.15 Beta, but both emit errors below and stop building:

```
Glyph AEacute seems to have been modified since last time checkoutlinesufo processed this font.
Glyph AEacute.sc seems to have been modified since last time checkoutlinesufo processed this font.
Glyph AEmacron seems to have been modified since last time checkoutlinesufo processed this font.
Glyph AEmacron.sc seems to have been modified since last time checkoutlinesufo processed this font.
Glyph Aacute seems to have been modified since last time checkoutlinesufo processed this font.
Glyph Aacute.sc seems to have been modified since last time checkoutlinesufo processed this font.
Glyph Abreve seems to have been modified since last time checkoutlinesufo processed this font.
Glyph Abreve.sc seems to have been modified since last time checkoutlinesufo processed this font.
Glyph Abreveacute seems to have been modified since last time checkoutlinesufo processed this font.
Glyph Abreveacute.sc seems to have been modified since last time checkoutlinesufo processed this font.
(additional messages omitted)
```

Did I miss any step?

**Comment by medicalwei** [comment]
I tried to add `checkoutlinesufo $font_ufo --clear-hash-map` of the UFO file in order to continue building fonts, the fonts can be built with a lot of unhinted glyphs warnings.  Is it intended?

I want the fonts can be built functionally the same, in order to check if the source code can produce the font, and to get away from the "Reserved Font Names" license restriction.

Also, is it possible to build fonts from Masters instead of from interpolated instances?

**Comment by miguelsousa** [comment]
The fonts should build now with the latest *afdko* version (3.0.1) using the `build.sh` script.

> is it possible to build the same output from Masters instead of from interpolated instances?

No. The UFO masters alone don't have all the metadata necessary to build the OTFs.
