### ISSUE TITLE
Add support for IPA affricate ligatures

### ISSUE THREAD

**Issue by AshtarBalynestjar** [adobe-fonts/source-sans-pro#174]
The representation of affricate consonants in the IPA is somewhat problematic. Because they indicate a transition between a stop and a fricative articulation, they’re prototypically represented with sequences of two symbols: [ts tʃ dz dʒ] etc. However, because some languages distinguish stop-fricative sequences from actual affricates, several solutions have been proposed. The one currently accepted by the IPA is to connect both glyphs with a tie bar: [t͡s d͡z] etc., but ligatures such as [ʦ ʣ] etc. are still very often seen in the literature, especially in dictionaries and in Chinese linguistics. Source Sans currently supports two of these: U+02A4 ʤ and U+02A7 ʧ.

Still missing are:
U+02A3 ʣ (= [d͡z]), 
U+02A5 ʥ (= [d͡ʑ]),
U+AB66 ꭦ (= [d͡ʐ], added in Unicode 12.0),
U+02A6 ʦ (= [t͡s]),
U+02A8 ʨ (= [t͡ɕ]),
U+AB67 ꭧ (= [t͡ʂ], added in Unicode 12.0).

**Comment by pauldhunt** [comment]
Fixed in [version 3.028](https://github.com/adobe-fonts/source-sans-pro/releases/tag/3.028R).
