### ISSUE TITLE
Help with translating name strings for stylistic sets & character variant features

### ISSUE THREAD

**Issue by pauldhunt** [adobe-fonts/source-sans-pro#175]
I’m wanting to add some descriptive names to the stylistic set and character variant features for the next release and would like some help translating the strings into Greek (EL), Russian (RU), and any other languages that you might like to help with. For those of you who have expertise in foreign languages can you either 1) review the current strings and suggest any edits you deem necessary, or 2) provide translations in your own language.

I've gotten help with the Greek strings, and taken a stab at some of the Russian strings but for those left as "перевод?" I didn't know where to start, so any help is appreciated. So without further ado, here are the strings in their current state:

EN: "Serifed I (⇧ i)"
EL: "Ι με πατούρα (⇧ ι)"
RU: "І с засечками (⇧ і)"

EN: "Simple a"
EL: "Απλό a"
RU: "Простой а"

EN: "Simple g"
EL: "Απλό g"
RU: "Простой g"

EN: Simple l (⇩ L)
EL: "Απλό l (⇩ L)"
RU: "Простой ӏ (⇩ Ӏ)"

EN: "Serifed a"
EL: "a  με πατούρα"
RU: "а с засечкам"

EN: "Centered ogoneks [ Ą Ę ą ę ų ] (Na-Dené)"
EL: "Κεντρικά ογκονεκ [ Ą Ę ą ę ų ] (Να-Ντενέ)"
RU: "Огонэки центрированные [ Ą Ę ą ę ų ] (На-Дене)"

EN: "x-height glottal stop [ ʔ ] (Na-Dené)"
EL: "Μικρή γλωττιδική στάση [ ʔ ] (Να-Ντενέ)"
RU: "Гортанная остановка короткая [ ʔ ] (На-Дене)"

EN: "N-shaped Eng [ Ŋ ] (Sami)"
EL: "Γράμμα Ενγκ σε σχήμα Ν [ Ŋ ] (Σάμη)"
RU: "перевод?"

EN: "Greek alternates for phonetic transcription [ ɑ ꞵ ɣ ɩ ʊ ɸ ꭓ ] (IPA)"
EL: "Εναλλακτικά φωνητικά γράμματα [ ɑ ꞵ ɣ ɩ ʊ ɸ ꭓ ] (ΔΦΑ)"
RU: "перевод?"

EN: "Greek cursive beta [ β ]"
EL: "Ρέων β"
RU: "Греческая бета скорописная [ β ]"

EN: "Greek alternate theta [ θ ]"
EL: "Εναλλακτικό θ"
RU: "Греческая тета альтернативная [ θ ]"

EN: "Greek alternate phi [ φ ]"
EL: "Εναλλακτικό φ"
RU: "Греческая фита альтернативная [ φ ]"

EN: "Cyrillic lowercase alternates with ascenders [ ж к ю ] (Bulgarian)"
EL: "Κυριλλικά μικρά γράμματα με κάθετη επέκταση [ ж к ю ] (Βουλγαρικά)"
RU: "перевод? [ ж к ю ] (Болгарские)"

EN: "Cyrillic cursive be [ б ] (Serbian)"
EL: "Κυριλλικό ρέων μπε [ б ] (Σέρβικα)"
RU: "Кириллический скорописний б (Сербский)"

EN: "Cyrillic cursive forms [ в г д з и й п т ц ш щ ѝ ]"
EL: "Κυριλλικά ρέων γράμματα [ в г д з и й п т ц ш щ ѝ ]"
RU: "Кириллические скорописные буквы [ в г д з и й п т ц ш щ ѝ ]"

EN: "Cyrillic geometric forms [ Д Л Љ д л љ ]"
EL: "Κυριλλικά γεωμετρικά γράμματα [ Д Л Љ д л љ ]"
RU: "Кириллические геометрические буквы [ Д Л Љ д л љ ]"

EN: "Cyrillic simple forms [ Ж К ж к ӏ ]"
EL: "Κυριλλικά απλά γράμματα [ Ж К ж к ӏ ]"
RU: "Кириллические простые буквы [ Ж К ж к ӏ ]"

EN: "Capital figures"
EL: "Κεφαλαίοι αριθμοί"
RU: "перевод?"

EN: "Dotted zero [ 0 ]"
EL: "Μηδέν με κεντρική τελεία [ 0 ]"
RU: "Пунктир ноль [ 0 ]"

EN: "Slashed zero [ 0 ]"
EL: "Μηδέν με κάθετο[ 0 ]"
RU: "Зачеркнутый ноль [ 0 ]"

EL: "Εναλλακτικά β θ φ"

RU: "Геометрические Д Ж К Л Љ д ж к л љ ӏ"

RU: "Геометрические Д Л Љ д л љ 

RU: "Простые Ж К ж к ӏ"

**Comment by webdev** [comment]
EN: "Serifed I (⇧ i)"
EL: "Ι με πατούρα (⇧ ι)"
RU: "І с засечками (⇧ і)"

EN: "Simple a"
EL: "Απλό a"
RU: "Простая а" 

EN: "Simple g"
EL: "Απλό g"
RU: "Простая g"

EN: Simple l (⇩ L)
EL: "Απλό l (⇩ L)"
RU: "Простой ӏ (⇩ Ӏ)"

EN: "Serifed a"
EL: "a με πατούρα"
RU: "а с засечкам"

EN: "Centered ogoneks [ Ą Ę ą ę ų ] (Na-Dené)"
EL: "Κεντρικά ογκονεκ [ Ą Ę ą ę ų ] (Να-Ντενέ)"
RU: "Огонэки центрированные [ Ą Ę ą ę ų ] (На-Дене)"

EN: "x-height glottal stop [ ʔ ] (Na-Dené)"
EL: "Μικρή γλωττιδική στάση [ ʔ ] (Να-Ντενέ)"
RU: "Гортанная смычка короткая [ ʔ ] (На-Дене)"

EN: "N-shaped Eng [ Ŋ ] (Sami)"
EL: "Γράμμα Ενγκ σε σχήμα Ν [ Ŋ ] (Σάμη)"
RU: "N-образная"

EN: "Greek alternates for phonetic transcription [ ɑ ꞵ ɣ ɩ ʊ ɸ ꭓ ] (IPA)"
EL: "Εναλλακτικά φωνητικά γράμματα [ ɑ ꞵ ɣ ɩ ʊ ɸ ꭓ ] (ΔΦΑ)"
RU: "Греческие альтернативные для фонетической транскрипции [ ɑ ꞵ ɣ ɩ ʊ ɸ ꭓ ] (IPA)"

EN: "Greek cursive beta [ β ]"
EL: "Ρέων β"
RU: "Греческая бета скорописная [ β ]"

EN: "Greek alternate theta [ θ ]"
EL: "Εναλλακτικό θ"
RU: "Греческая тета альтернативная [ θ ]"

EN: "Greek alternate phi [ φ ]"
EL: "Εναλλακτικό φ"
RU: "Греческая фита альтернативная [ φ ]"

EN: "Cyrillic lowercase alternates with ascenders [ ж к ю ] (Bulgarian)"
EL: "Κυριλλικά μικρά γράμματα με κάθετη επέκταση [ ж к ю ] (Βουλγαρικά)"
RU: "Строчные альтернативные кириллические с восходящими [ ж к ю ] (Болгарские)"

EN: "Cyrillic cursive be [ б ] (Serbian)"
EL: "Κυριλλικό ρέων μπε [ б ] (Σέρβικα)"
RU: "Кириллическая курсивная б (Сербский)"

EN: "Cyrillic cursive forms [ в г д з и й п т ц ш щ ѝ ]"
EL: "Κυριλλικά ρέων γράμματα [ в г д з и й п т ц ш щ ѝ ]"
RU: "Кириллические курсивные буквы [ в г д з и й п т ц ш щ ѝ ]"

EN: "Cyrillic geometric forms [ Д Л Љ д л љ ]"
EL: "Κυριλλικά γεωμετρικά γράμματα [ Д Л Љ д л љ ]"
RU: "Кириллические геометрические буквы [ Д Л Љ д л љ ]"

EN: "Cyrillic simple forms [ Ж К ж к ӏ ]"
EL: "Κυριλλικά απλά γράμματα [ Ж К ж к ӏ ]"
RU: "Кириллические простые буквы [ Ж К ж к ӏ ]"

EN: "Capital figures"
EL: "Κεφαλαίοι αριθμοί"
RU: "Заглавные буквы"

EN: "Dotted zero [ 0 ]"
EL: "Μηδέν με κεντρική τελεία [ 0 ]"
RU: "Ноль с пунктиром [ 0 ]"

EN: "Slashed zero [ 0 ]"
EL: "Μηδέν με κάθετο[ 0 ]"
RU: "Перечеркнутый ноль [ 0 ]"

EL: "Εναλλακτικά β θ φ"

RU: "Геометрические Д Ж К Л Љ д ж к л љ ӏ"

RU: "Геометрические Д Л Љ д л љ

RU: "Простые Ж К ж к ӏ"
