### ISSUE TITLE
Cyrillic font files

### ISSUE THREAD

**Issue by sweinstein22** [adobe-fonts/source-sans-pro#176]
Hi, I've downloaded the latest release and it looks like the cyrillic symbols aren't included. Is there somewhere I could download the font files for the cyrillic alphabet? Thanks!

**Comment by frankrolf** [comment]
If you downloaded from https://github.com/adobe-fonts/source-sans-pro/releases, Cyrillic characters should be included in the Roman (not Italic) font files. 
See here for example typesetting in Cyrillic: https://adobe-fonts.github.io/source-sans-pro/

**Comment by sweinstein22** [comment]
Thank you!
