### ISSUE TITLE
Some issues when I tried to install. Is it OK to use?

### ISSUE THREAD

**Issue by AlsoScratch** [adobe-fonts/source-sans-pro#177]
<img width="624" alt="Screenshot 2019-08-29 at 7 47 19 PM" src="https://user-images.githubusercontent.com/48752273/63937835-f45a3080-ca95-11e9-9327-fb561239e542.png">

**Comment by AlsoScratch** [comment]
Oh sorry, was installing both OTF and TTF by mistake.

**Comment by frankrolf** [comment]
In addition to that, native support for variable .otf files will only start with macOS 10.15 (which has not yet been publicly released).

**Comment by AlsoScratch** [comment]
I dragged the entire folder into Font Book, not realising that both OTF and TTF was in it.
