### ISSUE TITLE
Add support for combining double marks

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-sans-pro#179]
I found a photo taken from a Taiwanese Bible printed in Pe̍h-ōe-jī, on this image, I saw some texts has some marks over the _ng_ diagraph, but they are placed between two letters. 
https://commons.wikimedia.org/wiki/File:Taiwanese_Bible_Chim-gian_1933.jpg
NOTE: Click “Original file” to see the image after you visit the above page.

For example:
24:26 En͞g ha̍p-gi ê ōe ín-tap ê, Chhin-chhiūⁿ ēng chhùi kā lâng chim.
24:27 Lí tio̍h tāi-seng pi-pān gōa-thâu ê sū, Chhân-hn᷍g liāu-lí chheng-chhó, chiah thang khí-chhù.
26:8 Chhin-chhiūⁿ ēng chi̍t pò͘-tē-á pó-chio̍h khn​̀g ti chio̍h-tūi ê lāi-bīn.
(The above texts were typed with characters picked with BabelMap, I’m not clear what the contents are, but seen from the word chim-giân, I guess it should be the _Proverbs_  of the Old Testament)

To make them properly rendered with Source Sans Pro, you need to add support for combining double marks such as U+035E and U+1DCD.

**Comment by pauldhunt** [comment]
Fixed in [version 3.028](https://github.com/adobe-fonts/source-sans-pro/releases/tag/3.028R).
