### ISSUE TITLE
Some characters get corrupted when copy from PDF (created with apache fop)

### ISSUE THREAD

**Issue by jmarkert** [adobe-fonts/source-sans-pro#182]
When we generate PDFs with Apache fop the character “A” makes problems. When we copy the text from the PDF, the character “A” isn’t there. Its’s another unusable sign. 
[test.pdf](https://github.com/adobe-fonts/source-sans-pro/files/3819004/test.pdf)
In our example the text in the PDF is: “AUTOR: äöüßÄÖÜ”
When we copy and paste the text it is: “￿UTOR: äöüßÄÖÜ”

In our example we used 
source-sans-pro (regular), but the problem is the same in all the other fontstyles

**Comment by pauldhunt** [comment]
Can you tell me how this PDF was made?
Thanks
