### ISSUE TITLE
Small capitals clash with character variants

### ISSUE THREAD

**Issue by svenper** [adobe-fonts/source-sans-pro#183]
(Similar to #145)

Combining `smcp`, `c2sc` with `zero`, `ss02`, `cv06` etc. has no small caps for the alternate glyphs.

![1](https://user-images.githubusercontent.com/15199675/69101045-77b46e00-0a56-11ea-99d7-84c54867030b.png)

**Comment by pauldhunt** [comment]
Fixed in [version 3.028](https://github.com/adobe-fonts/source-sans-pro/releases/tag/3.028R).
