### ISSUE TITLE
Ṳ and ṳ (U+1E72 and U+1E73)

### ISSUE THREAD

**Issue by svenper** [adobe-fonts/source-sans-pro#184]
Used in romanizations of some variants of Chinese:

* [Pha̍k-fa-sṳ](https://en.wikipedia.org/wiki/Pha%CC%8Dk-fa-s%E1%B9%B3)
* [Pha̍k-oa-chhi](https://en.wikipedia.org/wiki/Pha%CC%8Dk-oa-chhi_romanization)
* [Bàng-uâ-cê](https://en.wikipedia.org/wiki/Foochow_Romanized)

Seeing how the comparable Pe̍h-ōe-jī (#157) is supported this small addition would make sense.

**Comment by frankrolf** [comment]
The answer to this may be similar to https://github.com/adobe-fonts/source-serif-pro/issues/40#issuecomment-447260002

**Comment by pauldhunt** [comment]
Will keep this in mind for future updates. Thanks.

**Comment by pauldhunt** [comment]
Fixed in [version 3.028](https://github.com/adobe-fonts/source-sans-pro/releases/tag/3.028R).
