### ISSUE TITLE
The font display a little obscure when it is less than 20px in desktop browser

### ISSUE THREAD

**Issue by codefarmerricky** [adobe-fonts/source-sans-pro#185]
As the title described the font display a little obscure when it is less than 20px in desktop browser as below screenshot
![image](https://user-images.githubusercontent.com/33510531/71960574-5428cb00-3230-11ea-956f-c859bafc77d5.png)
![image](https://user-images.githubusercontent.com/33510531/71960657-80444c00-3230-11ea-9c16-937a700437c1.png)

And when you make it bigger than 20px, it will be better than before as below screenshot.
![image](https://user-images.githubusercontent.com/33510531/71960764-c7324180-3230-11ea-884f-03bed989fc46.png)

But it is good in mobile phone and mac safari browser, I don't know why and I don't find a good way to resolve it.

I am sure I am using a good way to load source-sans-pro correctlly. So I want to konw is there any solution to make it looks better.

**Comment by pauldhunt** [comment]
@codefarmerricky Have you tried using the next heaviest weight? How small do you expect the fonts to scale well?

**Comment by codefarmerricky** [comment]
> @codefarmerricky Have you tried using the next heaviest weight? How small do you expect the fonts to scale well?

I expect 16px and 12px, I tried the font-weight:500 seems not reslove this problem. And if set too 600 it will be like bold and that's not my expection.

![image](https://user-images.githubusercontent.com/33510531/72128033-82331a00-33ac-11ea-87a8-cf8bb0459387.png)
![image](https://user-images.githubusercontent.com/33510531/72128040-8828fb00-33ac-11ea-86ff-e023a2e0907a.png)
But it looks good in Firefox as below 
![image](https://user-images.githubusercontent.com/33510531/72128110-c1616b00-33ac-11ea-82e5-052139f23654.png)

**Comment by pauldhunt** [comment]
@codefarmerricky if you are having different rendering with different browsers, it seems that it is most likely a browser issue and not a font issue, especially if you are finding good results in some browsers such as Firefox.
