### ISSUE TITLE
Source files missing in assets from release 3.006R

### ISSUE THREAD

**Issue by BoldMonday** [adobe-fonts/source-sans-pro#186]
The three assets provided with the [latest release](https://github.com/adobe-fonts/source-sans-pro/releases/latest) all contain generated binaries only.

**Comment by frankrolf** [comment]
They are in the master branch:
https://github.com/adobe-fonts/source-sans-pro/tree/master

**Comment by frankrolf** [comment]
Oh, perhaps you meant something else. Still, the source files should be obtainable via the tags in the master branch. Does that solve your problem?

**Comment by BoldMonday** [comment]
I was trying to download both the binaries and source files from the latest official release in order to analyse them.
But I discovered that both assets [source code (zip)](https://github.com/adobe-fonts/source-sans-pro/archive/3.006R.zip) and [source code (tar.gz](https://github.com/adobe-fonts/source-sans-pro/archive/3.006R.tar.gz) do not contain any source files at all, just the same generated binaries as [source-sans](https://github.com/adobe-fonts/source-sans-pro/releases/download/3.006R/source-sans-pro-3.006R.zip).

If it is hard to remedy for now then I hope it will be correct again for the next release.

**Comment by frankrolf** [comment]
The official Releases (e.g. https://github.com/adobe-fonts/source-sans-pro/releases/tag/3.006R) never contained any source files – it was always just the font binaries.

Releases are just glorified git tags, to which files can be attached via the GitHub interface. The link “source code” is misleading – it is created automatically by GitHub, and can’t be changed.

However, you still can use the tags to get to the source code in a similar manner:
https://github.com/adobe-fonts/source-sans-pro/releases/tag/3.006
