### ISSUE TITLE
U+2764 HEAVY BLACK HEART is a heavy black heart

### ISSUE THREAD

**Issue by emilazy** [adobe-fonts/source-sans-pro#187]
In most situations, this codepoint now renders as a [red emoji](https://emojipedia.org/red-heart/) (❤️), but in Source Sans Pro it's a traditional black heart, which tends to override emoji fonts and display the "old-school" presentation.

I'm not sure whether the best thing to do here is to remove the character, make it a colour glyph, or nothing at all, but I figured it was worth reporting.

**Comment by pauldhunt** [comment]
can you give me more information?
where & when does this happen?
what operating system are you using? what apps?

**Comment by emilazy** [comment]
I'm using Linux and Firefox, but I don't think this is an operating system configuration issue; as far as I can tell Source Sans Pro does contain this codepoint as a non-colour glyph, and therefore if you have font preferences like "Source Sans Pro, Noto Color Emoji" you'll incorrectly see non-emoji hearts. I'm suggesting that it's probably best for this to not be present so that emoji fonts can take precedence in all cases, or at least some other resolution.

**Comment by Manuel-K** [comment]
Have you tried giving the Emoji font a higher priority? If you specify it as "Source Sans Pro, Noto Color Emoji" then it is *correct* that you see Source Sans Pro's emojis. Everything else would be a bug.

Anyhow… I wouldn't be happy if Source Sans Pro would lose the emoji as I don't use a special font for them.
