### ISSUE TITLE
Space doesn't work in chrome > 80

### ISSUE THREAD

**Issue by michael-arvanitidis** [adobe-fonts/source-sans-pro#188]
Adding spaces doesn't seem to work in the newest version of chrome. 

Windows 10
Chrome 80.0.3987.87

https://v-fonts.com/fonts/source-sans-variable. I have tried editing the text on the page, as well as tried to add spaces and tabs via the devtools. 
![image](https://user-images.githubusercontent.com/8803354/74136653-b8073080-4bee-11ea-89ae-1fb745ac3504.png)

**Comment by fitojb** [comment]
I fail to see how this is a font bug—it’s about a web page, and it doesn’t reproduce in e.g. Firefox. To file a bug for the Chrome browser, go to crbug.com

**Comment by michael-arvanitidis** [comment]
Try using the font on a webpage and you’ll see that no spaces are shown. I would have made a jsfiddle but I can’t find a cdn for the font.

**Comment by michael-arvanitidis** [comment]
@fitojb a gif was the easiest way to show you what happens. The issue seems to be with the otf version. This is with chrome 80: https://im6.ezgif.com/tmp/ezgif-6-d112fe346bf7.gif. 
On Firefox Developer Edition 74 it throws an error on the otf-files, 
![image](https://user-images.githubusercontent.com/8803354/74273822-58ee0c80-4d11-11ea-95df-015609bdcf8e.png)

**Comment by frankrolf** [comment]
Following a quick conversation with @nicksherman, I just reproduced the same issue on the following pages:

https://v-fonts.com/fonts/source-serif-variable
https://v-fonts.com/fonts/acumin-variable-concept
https://v-fonts.com/fonts/minion-variable-concept

What those pages have in common:
- they all use the same CSS
- they all use CFF2 Variable Fonts

Although it looks like entering the space character is just ignored, there definitely is something happening – if I enter `AVAVAV` and insert a space between the letter pairs, the kerning is undone.

I am continuing my investigation.

**Comment by frankrolf** [comment]
I reproduced this in a different scenario (attached) and reported a bug to Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=1054371

**Comment by frankrolf** [comment]
Indeed a Chromium/FreeType bug. See comments in the Chromium bug linked above.
