### ISSUE TITLE
Glyph request: U+2236 ratio

### ISSUE THREAD

**Issue by tspiteri** [adobe-fonts/source-sans-pro#189]
U+2236 (ratio) is used in some applications as a time separator as it is a kind of raised colon that looks better between the digits. It is used in GNOME shell and also in the Windows 10 task bar.

Source Sans Pro already has the very similar U+2237 (proportion) which is kind of like a double ratio symbol.

**Comment by fitojb** [comment]
Those @GNOME and Windows designers are profoundly mistaken, because time is not a mathematical ratio :-P

But I support your request. This symbol is useful for UI strings like “1∶1 aspect ratio”.

**Comment by pauldhunt** [comment]
Fixed in [version 3.028](https://github.com/adobe-fonts/source-sans-pro/releases/tag/3.028R).
