### ISSUE TITLE
With heavy freetype hinting, in "spade" not enough space between 's' and 'p'

### ISSUE THREAD

**Issue by Mikolaj** [adobe-fonts/source-sans-pro#193]
First, thank you very much for the fonts. They are incredibly useful.

Second, on this screenshot in line 11, the red "spade" has not enough space between 's' and 'p' and perhaps a bit too much between 'p' and 'a'.

![image](https://user-images.githubusercontent.com/281893/90651378-3b0fe000-e23d-11ea-9a76-af3f786f4597.png)

This was rendered with the `TTF_RenderUTF8_Shaded` operation of SDL2-ttf (which uses the freetype library under the hood) at size 16px, based on the semibold .ttf font file I compiled from yesterday's version of your repo (using equally fresh afdko binary download) with `build.sh`, where the only modification I've done was replacing 'g' with the single-story version.

Interestingly the whole text looks completely different when the only change is using the .woff version of the file downloaded from http://google-webfonts-helper.herokuapp.com/fonts/source-sans-pro?subsets=latin,latin-ext, called source-sans-pro-v13-latin-ext_latin-600.woff:

![image](https://user-images.githubusercontent.com/281893/90652451-60511e00-e23e-11ea-966e-0b4b68df7e4f.png)

Here the spacing between 's' and 'p' is wider and between 'p' and 'a' narrower, which looks more consistent. [Edit: judging from "Last modified 2019-07-23 (v13)" they just use an older release of the font.]

However I strongly prefer the generally much larger spacing in the new version (because the font is very thick (and regular is too thin for dark colours on black background) and with bright colours on black background it's quite glaring, so bigger letter spacing helps a lot). Also, I love the fact that the right vertical line of 'H' is not narrower than the left one in the new version of the font (the inconsistency also happens in a few other glyphs in the version from http://google-webfonts-helper.herokuapp.com and also 't' and 'f' are single pixel thin, which is not necessarily bad, but different from the new version).

BTW, I've just checked and the silly look of the double-story 'g' is only a feature of the http://google-webfonts-helper.herokuapp.com version, it's not present in a pristine original compilation of the new version of your fonts I've just built for comparison:

![image](https://user-images.githubusercontent.com/281893/90655506-f470b480-e241-11ea-8c40-4f7cdf041564.png)

**Comment by frankrolf** [comment]
This very likely is a result of the rasterizer used. My suspicion is that this particular example of `spade` makes `p` and `a` coincide in a way that a new pixel is started for `a` – perhaps SDL2-ttf does not support sub-pixel letter spacing?

What happens if you slightly change the font size, or change the set width so `spade` moves to a different place?

**Comment by Mikolaj** [comment]
SDL2-ttf does antialising, but I don't know the exact method they use. If you look closely the spacing between the two pair of letters is always the same whenever they repeat in the text, so I'd rather suspect another feature of the rendering algorithm or the font definition or translation to TTF. 

I've tried the same, but rendered at 17px, not 16px and the spacing between 's' and 'p' is fine, while between 'p' and 'a' is still rather wide, but doesn't cause any discomfort in absence of reduced spacing it would contrast with.

![image](https://user-images.githubusercontent.com/281893/90660388-21bf6180-e246-11ea-8410-d7940f4ada19.png)

Anyway, if the rendering software is suspect, I can try to reproduce this with different system, e.g., browsers.

**Comment by Mikolaj** [comment]
Another data point: it doesn't happen with the Regular weight of the font (and the previous too little space after 's' and too much space before 'a' in semibold is not affected by the random translation from weight change earlier in the line):

![image](https://user-images.githubusercontent.com/281893/90678241-b766eb00-e25e-11ea-9698-30533c0c26a5.png)

**Comment by Mikolaj** [comment]
Update: I'm sorry to report that when I use OFT version of the font I compiled, the result is as condensed as the older version I got from http://google-webfonts-helper.herokuapp.com. OTOH, the "space" issue is not present. Perhaps the `otf2ttf` or `ttfcomponentizer` tool is currently broken? That's a sad news to me, because I hoped the increased space between letters in semibold variant is a feature, not a bug.

**Comment by frankrolf** [comment]
Would you consider testing the pre-compiled font files available under /releases?

**Comment by Mikolaj** [comment]
Yes, I failed to mention the "TTF/SourceSansPro-Semibold.ttf and WOFF/TTF/SourceSansPro-Semibold.ttf.woff" files are downloaded from the release branch of github. When I compile I don't get any .woff fonts (BTW, I'd love get hold of the script that creates them).

**Comment by frankrolf** [comment]
Thanks for all your research, this is very interesting!
The letter spacing within the fonts is deduced independent of any rasterizer, this means that printouts are made, screen display in different applications in taken into account, etcetera.

It is hard to optimize fonts for any rasterizer, because one can never predict the users' settings￼ and setup – even the most common rasterizer in the world is just one out of many.￼

Since @pauldhunt is currently working on a new release of￼ the fonts, he can have another look at the `sp` combination, however I think he has done his best to ensure proper spacing in most situations.￼
