### ISSUE TITLE
Static font files haven’t been updated in the release branch

### ISSUE THREAD

**Issue by throwaway571** [adobe-fonts/source-sans-pro#197]
Is Source Sans going to be a variable-only font now?

**Comment by pauldhunt** [comment]
It’s a mistake. I’m still in the process of updating the repo.

**Comment by pauldhunt** [comment]
I’ve updated all the fonts. Please check and see if you can access the updates.

**Comment by throwaway571** [comment]
@pauldhunt Yes, it’s fixed now. Thanks!
