### ISSUE TITLE
Line spacing in Source Sans 3 is greater than in Source Sans Pro

### ISSUE THREAD

**Issue by Kuphi** [adobe-fonts/source-sans-pro#204]
I downloaded Source Sans 3 (v3.0.28) to get the latest version and for future compatibility. In comparison to Source Sans Pro (v2.0.21 download from Google fonts) the line spacing is approximately 10% greater. I am using Windows 10, tried the ttf and otf. The greater line spacing persists in Libre Office and MS Office 2019. It can be fixed by changing line spacing in MS Office to "0.9". But cannot apply this workaround for all documents in our office. The font should be simple to use.

Question: Is the 10% greater line spacing on purpose or how can it be resolved?

Edit: The letters do have larger spaces on top and bottom, which results in greater line spacing.

**Comment by pauldhunt** [comment]
This is one of the reasons the family name has been changed, to make explicit that backward compatibility is NOT supported with this update.

**Comment by pauldhunt** [comment]
This is one of the reasons the family name has been changed, to make explicit that backward compatibility is NOT supported with this update.
