### ISSUE TITLE
Bold capitals render smaller than Regular capitals at certain point sizes

### ISSUE THREAD

**Issue by pauldhunt** [adobe-fonts/source-sans-pro#25]
The following information was received by me from Pablo García:

The rendering bug happens only for capital letters (caps / upper case). The px sizes affected are 24px, 23px, 22px, 21px, 10px and 9px. The exact problem is that bold face is 1px (or more) shorter than the normal face.

As you can see I have only tested up to size 25px.

The TTF / WOFF formats were forced both with the rendering bug (the screenshot would be exactly the same).

Environment:
Operating system: Ubuntu Lucid Lynx 64bits (x86_64, 2.6.32-46-generic)
Browsers: 
Google Chrome Version 26.0.1410.33 beta (GPU disabled), 
Chromium Version 27.0.1436.0 (187236) (GPU enabled)
Firefox 20
At Opera 12.14 the rendering issue is similar but happens instead at sizes: 16px, 13px.

We are using this CSS Link:
http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700

CSS obtained as default, WOFF format used:
@font-face {
font-family:
'Source Sans Pro';
font-style:
normal;
font-weight:
400;
src:
local('Source Sans Pro'),
local('SourceSansPro-Regular'),
url(http://themes.googleusercontent.com/static/fonts/sourcesanspro/v5/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff)
 format('woff');
}
@font-face {
font-family:
'Source Sans Pro';
font-style:
normal;
font-weight:
700;
src:
local('Source Sans Pro Bold'),
local('SourceSansPro-Bold'),
url(http://themes.googleusercontent.com/static/fonts/sourcesanspro/v5/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff)
 format('woff');
}

CSS obtained when forcing to TTF:
@font-face {
font-family:
'Source Sans Pro';
font-style:
normal;
font-weight:
400;
src:
local('Source Sans Pro'),
local('SourceSansPro-Regular'),
url(http://themes.googleusercontent.com/static/fonts/sourcesanspro/v5/ODelI1aHBYDBqgeIAH2zlNzbP97U9sKh0jjxbPbfOKg.ttf)
 format('truetype');
}
@font-face {
font-family:
'Source Sans Pro';
font-style:
normal;
font-weight:
700;
src:
local('Source Sans Pro Bold'),
local('SourceSansPro-Bold'),
url(http://themes.googleusercontent.com/static/fonts/sourcesanspro/v5/toadOcfmlt9b38dHJxOBGLsbIrGiHa6JIepkyt5c0A0.ttf)
 format('truetype');
}

![Chrome26_Ubuntu_Lucid_Lynx](https://f.cloud.github.com/assets/2119748/383023/6947e8fa-a609-11e2-8a30-d404650d3d4c.png)

![Opera12 14_Ubuntu_Lucid_Lynx](https://f.cloud.github.com/assets/2119748/383024/694be1b2-a609-11e2-81cb-0d61030c14e6.png)

**Comment by mattez** [comment]
Also discussed here: https://github.com/googlefonts/fontbakery/issues/120

**Comment by frankrolf** [comment]
Google Fonts usually serves outdated font versions, can you reproduce the waterfall with the latest release?

**Comment by mattez** [comment]
I made some test across browser and it looks like it is more problem of browser rendering. I looks different across browsers Chrome vs Ubuntu.

![selection_084](https://user-images.githubusercontent.com/143115/33429799-929064ae-d5ce-11e7-80b4-9b61f804cc1a.png)
![selection_085](https://user-images.githubusercontent.com/143115/33429800-92ac97b4-d5ce-11e7-813c-1480e5e1b56b.png)
![selection_086](https://user-images.githubusercontent.com/143115/33429801-92c81be2-d5ce-11e7-8e98-ce6eedd36d73.png)
![selection_087](https://user-images.githubusercontent.com/143115/33429802-92e24cf6-d5ce-11e7-8654-d7c7a0ff7fb7.png)
