### ISSUE TITLE
Issues with geometric shapes

### ISSUE THREAD

**Issue by moyogo** [adobe-fonts/source-sans-pro#39]
The regular geometric shapes should have the same visual impact.
Unicode also provides some large square or circles, medium squares, small squares, triangles or circles.
See http://www.unicode.org/reports/tr25/

The geometric shapes ■◆◉ \25A0\25C6\25C9 are way too small for regular size in Source Sans Pro, they should match the sizes of the following regular triangles.
▲△▶▷▼▽◀◁ \25B2\25B3\25B6\25B7\25BC\25BD\25C0\25C1 could be a bit bigger as well.
It’s less clear for ❒ \2752 what size it should have.

**Comment by adrientetar** [comment]
Why do geometric shapes have to be that big? It you look at how they are used in typesetting e.g. for dictionaries (see [here](http://2.bp.blogspot.com/_zcECmapKp5s/SxMBfBoQ0II/AAAAAAAAAO0/ob21sOPYXqQ/s1600/Fig13.png)), they need to have at most ~ height of capital letters (this is the case with Hoefler fonts Mercury & Chronicle, for instance &ndash; or Collins Fedra).

**Comment by moyogo** [comment]
This is what the glyphs mentioned look like in 1.050:
![source sans pro - geometric shapes - 1 050](https://cloud.githubusercontent.com/assets/1923747/5602545/e2c2b22e-934b-11e4-8ade-35c3cf6f8ff5.png)

This is what the glyphs mentioned look like in 2.010:
![source sans pro - geometric shapes - 2 010](https://cloud.githubusercontent.com/assets/1923747/5602548/00c676de-934c-11e4-96ad-b42179e203d8.png)

All the geometric shapes are now much larger and are so in a consistent manner. This matches their design in Source Han Sans fonts.

@adrientetar the black square in [your example] (http://2.bp.blogspot.com/_zcECmapKp5s/SxMBfBoQ0II/AAAAAAAAAO0/ob21sOPYXqQ/s1600/Fig13.png) is closer to x-height that cap-height.

**Comment by adrientetar** [comment]
I think Source Serif Pro does it right:

![a](https://cloud.githubusercontent.com/assets/1250894/5602567/8a72d6c0-9356-11e4-9547-866a8a3cceab.png)

I don't use Source Han Sans, the only thing I can say is that the current geometric symbols are just too large to be used in Latin publications.

**Comment by pauldhunt** [comment]
I’ll look at this again. It will help to know what the common use cases for these are in Western publications.

**Comment by adrientetar** [comment]
The [Mercury Text specimen slider](http://www.typography.com/fonts/mercury-text/overview/) presents some examples of uses.

Square is often used as end of paragraph mark, as list or overall decorative marker.

![](http://www.mairie-noiseau.fr/iso_album/leparisien_24-11-14002_765x570.jpg)

Some fonts even include variants of squares, diamond and circles fitted to the xheight as my example from a previous comment shows. Had a [thread](http://typedrawers.com/discussion/840/dingbats-geometric-shapes-whats-important) about this &ndash; FF Franziska has some fuss in this domain too.

![capture du 2015-01-14 22 03 15](https://cloud.githubusercontent.com/assets/1250894/5747561/2da0f7a6-9c39-11e4-9c45-2865e4f3e967.png)

These marks are used in running text so they imo shouldn't be larger than capitals.

**Comment by moyogo** [comment]
Based on "End Marks" and the illustration in https://books.google.com/books?id=dEbaAgAAQBAJ&pg=PT215 it should probably be enough to reduce the size of ■ 25A0 BLACK SQUARE and the likes a little bit and add ▪ 25AA BLACK SMALL SQUARE, ◼ 25FC BLACK MEDIUM SQUARE and some others.

**Comment by adrientetar** [comment]
The current black square of Source Sans Pro looks more like U+2B1B than U+25A0.

**Comment by erniemarch** [comment]
These have noticeably changed size in 3.006
