### ISSUE TITLE
Dollar sign is 'globbing up' at small sizes on-screen.

### ISSUE THREAD

**Issue by steveross1956** [adobe-fonts/source-sans-pro#43]
I've noticed the '$' behaving strangely on-screen at small sizes. Specifically, the top of the bar seems to be _"globbing up"_ with the top of the "S". Setting 10 pt semibold '$' in InDesign and then viewing at 125% seems to trigger it. _Hinting/alignment zone issue?_

![screen shot 2014-05-13 at 17 36 01](https://cloud.githubusercontent.com/assets/7461060/2965828/cb7b57a6-daff-11e3-874b-7645352e1e44.png)

**Comment by frankrolf** [comment]
I can confirm this is still happening with 2.020 OTFs, however now at 150%.
![screen shot 2018-02-07 at 15 42 31](https://user-images.githubusercontent.com/2049645/35947648-c851ac94-0c1d-11e8-90b7-91f8d5f80c30.png)

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084. Not seeing this behavior, so assuming it is fixed.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
