### ISSUE TITLE
IPA support

### ISSUE THREAD

**Issue by dpk** [adobe-fonts/source-sans-pro#44]
I see mentioned in #42 that you intend to add African language support to the fonts. Could you also take a look at what other glyphs you need to add to finish [IPA](http://en.wikipedia.org/wiki/International_Phonetic_Alphabet) support? The IPA is mostly Latin alphabet + African languages glyphs + rotated/flipped versions of those, + a small number of other glyphs.

Looking at the existing glyph complement of the fonts, I don't think it would be too hard to finish IPA support once African languages are added.

**Comment by pauldhunt** [comment]
@dpk Is the confusion with theta the only reason to make the bilabial click character wider, or are there other reasons? My reasoning for keeping it narrow is that if there is only a unicase version of the glyph, I have been treating these as lowercase letters to prevent them from drawing too much attention to themselves in running text.

**Comment by dpk** [comment]
Well, a wider character is also likely to be more recognizable to linguists and phoneticians. But apart from that, no.

**Comment by dylofish** [comment]
U+02A4 and U+02A7 seem to be missing. I consider those to be very important for Speech Pathology language transcription.

**Comment by brawer** [comment]
Here’s a [PDF of Source Sans Pro version 2.020](https://github.com/adobe-fonts/source-sans-pro/files/668541/SourceSansPro-IPA.pdf), rendering an [IPA test page](https://github.com/googlei18n/noto-source/blob/master/test/und-fonipa.html) which I originally made for Noto (another open-source font). Consider improving the tie bars in Source Sans Pro:

![image](https://cloud.githubusercontent.com/assets/1527880/21423336/c1238d82-c83c-11e6-9909-be8a7069217e.png)

Admittedly my [IPA test page](https://github.com/googlei18n/noto-source/blob/master/test/und-fonipa.html) is rather incomplete; feel free to add more test cases.

**Comment by erniemarch** [comment]
release notes list Latin Letter Ain (U+1D25), which is in Unicode charts as the full size version. The glyph in the font is marked U+1D5C, which according to the charts is the superior form (which is not in the font). Please check the unicode for this glyph.

Also, tesh digraph (U+02A7) has no outline or width in romans.

**Comment by pauldhunt** [comment]
@erniemarch the unicode value listed in the release notes is wrong, it should be `LATIN LETTER AIN (U+1D5C)`

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
