### ISSUE TITLE
styleMapFamilyName?

### ISSUE THREAD

**Issue by davelab6** [adobe-fonts/source-sans-pro#47]
In https://github.com/adobe-fonts/source-sans-pro/blob/master/Roman/Regular/font.ufo/fontinfo.plist#L92-L93 the `styleMapFamilyName` seems odd....

```
<key>styleMapFamilyName</key>
<string>368 : SourceSansPro_0.ufo / SourceSansPro_1.ufo</string>
```

This is the same in all UFOs in this repo - https://github.com/adobe-fonts/source-sans-pro/search?utf8=%E2%9C%93&q=styleMapFamilyName

Is this value correct? If not, is it corrected elsewhere?

**Comment by adrientetar** [comment]
@miguelsousa Why was this closed?

**Comment by miguelsousa** [comment]
@adrientetar Because https://github.com/adobe-type-tools/python-scripts/commit/b0327be15efb6df1368d4466f7a71abf2add3c6e

**Comment by adrientetar** [comment]
Oh I see, I saw it still in the UFO instances.

**Comment by miguelsousa** [comment]
It should be gone in the upcoming revision.
