### ISSUE TITLE
Quotedoublebase („) has too less right bearing in italic variants

### ISSUE THREAD

**Issue by charakterziffer** [adobe-fonts/source-sans-pro#49]
All italics of Source Sans Pro seem to have the common problem that the space right of the quotedoublebase (U+201E) is too small. When used in German texts the quote sticks at the following letter, for example in „Ernsthaft?“ – „Leider ja.“

**Comment by aaaxx** [comment]
Any news on this? When's the next version due?

**Comment by pauldhunt** [comment]
I will try to have a fix for this out as soon as possible. Sorry for keeping you waiting so long.

**Comment by aaaxx** [comment]
No problem, and much appreciated.

**Comment by miguelsousa** [comment]
Fixed in italics version 1.075.
