### ISSUE TITLE
bower.json provided, but `source-sans-pro` isn't registered

### ISSUE THREAD

**Issue by andrewmcwatters** [adobe-fonts/source-sans-pro#51]
Hey Adobe,

I've noticed `bower.json` is provided with the latest release. Awesome stuff! But I was sad to see that I couldn't just `bower install --save source-sans-pro`. :(

Am I wrong to assume that you folks might be registering the repo soon? I'm hoping you do, many people use bower, and it would be very helpful to have this typeface readily available for use in projects through the package manager.

I noticed this mentioned in #35, and here's my "pretty please" in response to [this](https://github.com/adobe-fonts/source-sans-pro/issues/35#issuecomment-26634388).

All it takes is a `bower register https://github.com/adobe-fonts/source-sans-pro.git`. In fact, anyone can do it, but it would probably be rude for someone to do it if he or she wasn't the actual maintainer of the project.

**Comment by patbaker82** [comment]
It would be really nice if we could have a supported bower release
