### ISSUE TITLE
Sub- and superscript "+" and "−"

### ISSUE THREAD

**Issue by tomkeb** [adobe-fonts/source-sans-pro#55]
Would it be possible to add sub- and superscript "+" and "−" characters? I find these particularly useful for writing good-looking chemical formulas in programs that don't support true sub- and superscript (such as LibreOffice Impress)…

![formulae](https://cloud.githubusercontent.com/assets/10372446/5596511/65672258-9290-11e4-8c48-a94289b54021.png)

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084. These are now present.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
