### ISSUE TITLE
Support more writing systems?

### ISSUE THREAD

**Issue by davelab6** [adobe-fonts/source-sans-pro#56]
I work as a consultant for various organizations, including in recent years the Google Fonts team, and I'm pleased to say that Google is offering some limited financial assistance to commission qualified designers to improve popular libre-licensed font projects, especially to increase their language support.

https://github.com/adobe-fonts/source-sans-pro#getting-involved says to email Paul directly to discuss how to get involved, and after a brief discussion with him, I thought I'd file an issue here to ask the wider SSP community about what was important to you all. 

What would you like to see added to Source Sans Pro?

Regarding language support, its a big effort, and any single organization's budget is always limited, so I'd love to know if anyone subscribed here knows of any companies or other organizations who would like Source Sans or Serif to be extended to the following scripts, and would be willing to 'co-pay' with Google so that together we can all go further :) 

Arabic
Bengali
Gujarati
Gurmuhki
Hebrew
Kannada
Malayalam
Sinhala
Tamil
Telugu
Thai

To recap, from what I can gather, so far the project has been extended from Latin to IPA, Greek and Cyrillic by @pauldhunt for the upright styles, and by Marc Weymann (who I couldn't find on Github just yet) for small caps in the upright styles. It seems to me that a good thing would be to round-out those additions to all styles in the family; certainly the Google Fonts API would benefit from that, to provide consistent web font families.

There are also the sister projects led by @frankrolf , Source Serif Pro, and it has some 'evening out' issues already filed for [italics](https://github.com/adobe-fonts/source-serif-pro/issues/4) and [IPA, Greek and Cyrillic](https://github.com/adobe-fonts/source-serif-pro/issues/2)

There's also the Source Han Pro project, which was developed by a cross-industry collaboration to support all of CJK, and has been released as a separate family. That seems typical of Adobe's multi-script families, such as Myriad which has "Myriad Hebrew" and "Myriad Arabic" and those include scaled down Latin glyphs that harmonize and are sort of secondary to the script in the family name.

In that direction, there are some 'cousins' too; new projects not directly affiliated with Adobe, for scripts not directly related to Latin, but designed to be compatible or harmonious with SSP, like @khmertype 's [Lao Sans Pro](https://github.com/khmertype/LaoSansLight) and [Myanmar Sans Pro](https://github.com/khmertype/MyanmarSansPro), and @erinmclaughlin's sketch of a [Source Sans Pro compatible Devanagari](https://github.com/erinmclaughlin/SSPDevanagari). I wonder if there are there any other projects like these cooking silently behind closed doors? :)

**Comment by adrientetar** [comment]
> There are also the sister projects led by @frankrolf , Source Serif Pro, and it has some 'evening out' issues already filed for italics and IPA, Greek and Cyrillic

Also Source Serif Pro does not have small caps, unlike Source Sans Pro uprights.

**Comment by frankrolf** [comment]
@adrientetar @davelab6 Since Source Sans and Source Serif are complementary projects, both aim for the same set of supported languages and character sets.
Source Sans is more comprehensive because it was started earlier, but Small Caps, Italics etc. are all on my personal to-do list for Source Serif.
