### ISSUE TITLE
Support thin space, hair space and zero-width space

### ISSUE THREAD

**Issue by aaaxx** [adobe-fonts/source-sans-pro#58]
U+2009, U+200A and U+200B respectively.

It would be nice to have them as part of the font.

**Comment by adrientetar** [comment]
@aaaxx What do you use hair space and zero-width space for? Hair space I already have in my fonts (used in French typography), the others I was wondering.

**Comment by moyogo** [comment]
@adrientetar zero-width space can be used in typesetting between integers and fractions: 1​1/2 (1 and a half with a ZWSP) vs 11/2 (11 halves without ZWSP) with the fraction feature on.
It can also be used in typesetting to separate words in writing systems that don't necessarily have blank space between words like Burmese, Khmer, Lao, Thai, ’Phags-pa or maybe even Chinese or Japanese.

**Comment by BadJokeGuy** [comment]
@adrientetar I use zero-width space a lot for long URLs that need to be wrapped (e.g. for justified text) but also need to remain legible when typed in by a reader that only has got access to the printed version of a paper (as opposed to just clicking the link in an online version). In this case, zero-width space seems to be the best way to automatically wrap these URLs at places that still make sense to an educated reader, avoiding ambiguities. Introducing hyphens in an URL could be misdirecting the reader to a wrong online resource.
For example, consider a paper that quotes its references, and among those might be:
Doe, John, and Roe, Jane: Example of Open Access Pusblishing. In: Journal of Foobar, 2012, Issue 9, page 22. Online resource: http://​lorem.​ipsum.​example.​com/​dolor/​sit/​amet/​consectetur.html​#adipsici
This long URL is likely to need line wrapping in a typical journal that uses a two column layout.
(Of course, only the anchor text would contain the zero-width spaces in this case, not the actual "clickable" link that would be put into a PDF of the paper. I hope this example remains intact when posting through this comment form.)

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084. These are now present.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
