### ISSUE TITLE
No unicode values on any glifs in UFO masters

### ISSUE THREAD

**Issue by weiweihuanghuang** [adobe-fonts/source-sans-pro#59]
Are the unicode values assigned by another file or process? Or is this a bug?

**Comment by frankrolf** [comment]
The Unicode values are assigned at build time though `makeotf`, which reads that data from the GlyphOrderAndAliasDB file.

**Comment by weiweihuanghuang** [comment]
Not a bug then! But how does it know which unicode to assign each glyph, or is it in the order?

**Comment by weiweihuanghuang** [comment]
And what's the best way to get the unicode values into the .UFO if we wanted to use a .UFO editor…?

**Comment by frankrolf** [comment]
There is a list of standardized glyph names, commonly know as the `agl` (Adobe Glyph List).
Within the FDK, this data is called via the `agd` module. 
[You can search the FDK repo for `agl` for more information](https://github.com/adobe-type-tools/afdko/search?utf8=✓&q=agl).
The AGL even has a [Wikipedia entry].(http://en.wikipedia.org/wiki/Adobe_Glyph_List)

Additionally, here is a listing of the AL1 – AL5 character sets we use:
https://github.com/adobe-type-tools/adobe-latin-charsets

If you want to get Unicode values in a UFO I suggest the Robofab method `glyph.autoUnicodes()`; which also relies on the info given in the `agl` list.

**Comment by miguelsousa** [comment]
> But how does it know which unicode to assign each glyph, is it in the 2nd column (standardised naming)?

By processing the names in the 1st column. The Unicode values for standard names are assigned according to the [AGLFN](http://sourceforge.net/projects/aglfn.adobe/files/). Names that follow the format `uniXXXX` will be Unicode-encoded as `XXXX`. GlyphOrderAndAliasDB entries that have a value in the 3rd column (e.g. glyph `f_f`), will get that Unicode value.

Glyphs with names that don't follow any of the rules above, will get no Unicode value.

**Comment by weiweihuanghuang** [comment]
Thanks for the clear explanation. Why are the unicode values not encoded into the .UFO though?

**Comment by miguelsousa** [comment]
Because they aren't needed. The OTFs are built with `makeotf` and this tool gets all the Unicode information it needs from the GlyphOrderAndAliasDB file.
