### ISSUE TITLE
Italic "double low-9 quotation mark" spacing

### ISSUE THREAD

**Issue by aaaxx** [adobe-fonts/source-sans-pro#60]
Italic "double low-9 quotation mark" (U+201E) needs more built-in padding on the right side (or kerning?). Right now it runs into other characters.

**Comment by tomkeb** [comment]
It has already been covered in this bug: https://github.com/adobe-fonts/source-sans-pro/issues/49

**Comment by aaaxx** [comment]
Oops, sorry.
