### ISSUE TITLE
For which platforms must OS/2 Typo Vertical Metrics sum to UPM?

### ISSUE THREAD

**Issue by davelab6** [adobe-fonts/source-sans-pro#61]
In https://github.com/adobe-fonts/source-sans-pro/blob/master/Roman/Black/features#L25 you have

> NOTE: For cross-platform consistency, `OS/2.TypoAscender` and `OS/2.TypoDescender` must add up to the font's UPM value

Do you know which platforms are inconsistent in their handling of these values?

**Comment by miguelsousa** [comment]
No. But I have a vague recollection that was neither Mac or Windows.

**Comment by davelab6** [comment]
Thanks you Miguel! :)
