### ISSUE TITLE
Language support 

### ISSUE THREAD

**Issue by jasoncostello** [adobe-fonts/source-sans-pro#65]
This issue is a discussion question, I'm not reporting a bug. I'm trying to find a succinct list of languages that Source Pro supports supports. Any chance somebody might be able to relay that here or point me in the right direction?

**Comment by popbones** [comment]
Hope this would help. According to the font information from the Font Book for Source Han Sans, it support these languages:

Afrikaans, Albanian, Asu, Azerbaijani, Basque, Bemba, Bena, Bosnian, Breton, Catalan, Chiga, Congo Swahili, Cornish, Croatian, Czech, Danish, Dutch, Embu, English, Esperanto, Estonian, Faroese, Filipino, Finnish, French, Galician, German, Gusii, Hawaiian, Hungarian, Icelandic, Igbo, Indonesian, Irish, Italian, Kabuverdianu, Kalaallisut, Kalenjin, Kamba, Kikuyu, Kinyarwanda, Latvian, Lithuanian, Luo, Luyia, Machame, Makhuwa-Meetto, Makonde, Malagasy, Malay, Maltese, Manx, Meru, Morisyen, North Ndebele, Norwegian Bokmål, Norwegian Nynorsk, Nyankole, Oromo, Polish, Portuguese, Romanian, Romansh, Rombo, Rundi, Rwa, Samburu, Sango, Sangu, Sena, Shambala, Shona, Slovak, Slovenian, Soga, Somali, Spanish, Swahili, Swedish, Swiss German, Taita, Teso, Tongan, Turkish, Turkmen, Uzbek, Vietnamese, Vunjo, Welsh, Yoruba, Zulu

**Comment by jasoncostello** [comment]
Impressive language support. Now I love Source even more. 

Thanks @popbones :sparkles:

**Comment by miguelsousa** [comment]
@popbones you must not be using the [latest version of Source Sans Pro](https://github.com/adobe-fonts/source-sans-pro/releases/latest) because the romans **v2.010** have support for the Cyrillic and Greek scripts.

According to FontBook (Version 5.0; OS X 10.10), these are the languages missing from your list:
* Belarusian
* Bulgarian
* Ganda
* Greek
* Jola-Fonyi
* Kazakh
* Macedonian
* Mongolian
* Russian
* Serbian
* Tajik
* Ukrainian

**Comment by snds** [comment]
Is there a list of languages that will be added to the support list? Perhaps versions for CJK languages, Arabic, or Hebrew?

**Comment by miguelsousa** [comment]
@snds CJK languages are already supported via [Source Han Sans](https://github.com/adobe-fonts/source-han-sans). There are currently no plans to develop Arabic or Hebrew fonts.
