### ISSUE TITLE
Support for small triangle glyphs

### ISSUE THREAD

**Issue by robd** [adobe-fonts/source-sans-pro#67]
This is an enhancement request. I was wondering if it would be possible to add support for the following symbols:

BLACK UP-POINTING SMALL TRIANGLE (U+25B4)
BLACK RIGHT-POINTING SMALL TRIANGLE (U+25B8)
BLACK DOWN-POINTING SMALL TRIANGLE (U+25BE)
BLACK LEFT-POINTING SMALL TRIANGLE (U+25C2)

And perhaps the white versions for consistency: 

WHITE UP-POINTING SMALL TRIANGLE (U+25B5)
WHITE RIGHT-POINTING SMALL TRIANGLE (U+25B9)
WHITE DOWN-POINTING SMALL TRIANGLE (U+25BF)
WHITE LEFT-POINTING SMALL TRIANGLE (U+25C3)

The specific use case I have is wanting to use the black small down triangle 25BE in drop down menus as implemented by [Pure CSS](http://purecss.io/menus#dropdowns). AFAICT this [requires a font-face](http://unicode.johnholtripley.co.uk/25BE/) on Samsung / Sony devices. Since I am already using source-sans-pro as my main font this would fix drop down menus on these devices without me having to custom patch this glyph from another font. Pure CSS also requires the small right triangle 25B8.

For me, the ideal size / styling / position would be based on LucidaGrande shipped with OSX.

Is there any straightforward way I can merge these glyphs from LucidaGrande and rebuild the font? I tried this using FontForge, but the arrow size was [too large when I copied it across](http://stackoverflow.com/questions/31493834/how-can-i-import-a-glyph-from-lucida-grande-into-source-sans-pro-for-use-on-the). Also, I would need to recreate the EOT, WOFF files etc, so I guess I would need to edit the source and rebuild the fonts.

For reference, the following are already supported:

BLACK UP-POINTING TRIANGLE (U+25B2) 
WHITE UP-POINTING TRIANGLE (U+25B3) 
BLACK RIGHT-POINTING TRIANGLE (U+25B6)
WHITE RIGHT-POINTING TRIANGLE (U+25B7)
BLACK DOWN-POINTING TRIANGLE (U+25BC)
WHITE DOWN-POINTING TRIANGLE (U+25BD)
BLACK LEFT-POINTING TRIANGLE (U+25C0)
WHITE LEFT-POINTING TRIANGLE (U+25C1)

**Comment by robd** [comment]
Just to follow up here, @pauldhunt pointed out to me via email that these have already been [added to source-code-pro](https://github.com/adobe-fonts/source-code-pro/issues/51):

> I believe these glyphs are now in Source Code Pro, so it will be easy to add them to the Source Sans fonts the next time they are updated.

I am happy to do this legwork if that helps, but I'm new to fonts, so not sure what's involved.

**Comment by pauldhunt** [comment]
@robd I should have marked this issue closed with the latest release as these characters are all supported from [version 3.006](https://github.com/adobe-fonts/source-sans-pro/releases/tag/3.006R)
