### ISSUE TITLE
Is it possible to merge all the variations into one font file?

### ISSUE THREAD

**Issue by shobhitg** [adobe-fonts/source-sans-pro#68]
Hi,

Right now we would end up having 12 separate requests if I use a character of every variation.

In my network tab, I see one request for each one of these files:

* SourceSansPro-SemiboldIt.otf
* SourceSansPro-Semibold.otf
* SourceSansPro-Regular.otf
* SourceSansPro-LightIt.otf
* SourceSansPro-Light.otf
* SourceSansPro-It.otf
* SourceSansPro-ExtraLightIt.otf
* SourceSansPro-ExtraLight.otf
* SourceSansPro-BoldIt.otf
* SourceSansPro-Bold.otf
* SourceSansPro-BlackIt.otf
* SourceSansPro-Black.otf

Is it possible to merge these files into one to reduce network calls from browser?

thanks,
Shobhit

**Comment by pauldhunt** [comment]
Dear Shobit,

Can you please give a higher-level explanation of what it is you are trying to accomplish and what seems to be the issue?

It sounds like you are asking if all the styles of one character can be put in a single font. Of course this is possible, but that would involve modifying the the font files beyond the scope of this project and seems to be something that would be of only very specific use to you (if i am, in fact, understanding your issue correctly). As accomplishing what I have described would involve quite a lot of work to benefit yourself only, I would suggest that this is an ideal situation in which you should fork the project to create the kind of fonts you are looking for. Please let me know if I have misunderstood your request.

Best,

Paul

**Comment by shobhitg** [comment]
I was hoping this would be something simple. But from your response I now get that its not simple.

But I can't be the only one with this kind of requirement.
Basically I wish to pre-load fonts for extreme performance reasons.

It just occurred to me that could convert all the fonts to base64 and include them in css. Now I only see one single network request for the css file. I just tried it and it works perfect.

Thanks for taking time to respond to my question.

**Comment by miguelsousa** [comment]
@shobhitg you could perhaps try using this OpenType collection font file, [SourceSansPro.ttc](http://cl.ly/cmEk), which I made with the FDK's `otf2otc` tool.
I just don't know if the browsers will support it, and how to access each individual style from within CSS.

**Comment by moyogo** [comment]
Browsers don’t support TTC as a web font format yet.
