### ISSUE TITLE
Greek phi symbol 03D5 ϕ should have a full stroke

### ISSUE THREAD

**Issue by moyogo** [adobe-fonts/source-sans-pro#70]
The description of 03D5 ϕ in the Unicode chart http://www.unicode.org/charts/PDF/U0370.pdf is:
• used as a technical symbol, with a stroked glyph
• maps to 'phi1' symbol entities

03D5 ϕ should have a full stroke (like 03C6 φ currently is).

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084. This is now the full stroke version.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
