### ISSUE TITLE
[brackets] Query reg. latest release

### ISSUE THREAD

**Issue by abose** [adobe-fonts/source-sans-pro#71]
Hi,
 We are planning to upgrade the source sans font in brackets. I see that a pre-release font has been drafted.
When would a new release of source-sans-pro will be avilable.
Thanks and regards,
arun,
Brackets.io

**Comment by miguelsousa** [comment]
@abose we are on the last stages of QE. A new release is likely to happen this week.

**Comment by abose** [comment]
Thanks. Waiting for the release :+1:

**Comment by miguelsousa** [comment]
The newest release is live.

**Comment by abose** [comment]
Thanks :)
