### ISSUE TITLE
How are the source font.ttf files generated?

### ISSUE THREAD

**Issue by khaledhosny** [adobe-fonts/source-sans-pro#78]
This is similar to #77.

The source `font.ttf` files are committed into the repository and are not generated from the UFO sources at built time, so my question is how they are generated (tools used etc) and whether they are touch manually or not.

**Comment by miguelsousa** [comment]
They are created from the `font.ufo` fonts via FontLab and using the [`convertToTTF.py`](https://github.com/adobe-type-tools/fontlab-scripts/tree/master/TrueType) macro.
The `font.ttf` files are not modified after that.

**Comment by khaledhosny** [comment]
Thanks, too bad it depends on FontLab, but that is life.

**Comment by miguelsousa** [comment]
@khaledhosny we plan to shift that dependency to RoboFont at some point. Unfortunately the FDK doesn't have a tool to make TTFs (from scratch or thru conversion), so we won't be able to move away from 3-party solutions in the foreseeable future.

**Comment by moyogo** [comment]
There might be some tools to do that soon. @jamesgk is working on that for https://github.com/google/roboto/pull/53
