### ISSUE TITLE
Support for U+1E40 and U+1E41 - Latin M/m with dot above (missing in italics)

### ISSUE THREAD

**Issue by molefunk** [adobe-fonts/source-sans-pro#81]
This would make all our diacritics requirements complete. :)

**Comment by pauldhunt** [comment]
Will add this to the next update.

**Comment by atomparticle** [comment]
How's that next update coming? :) Do you accept pull requests for things like this, btw?

**Comment by miguelsousa** [comment]
> Do you accept pull requests for things like this, btw?

Yes. Update the UFO masters, the `GlyphOrderAndAliasDB` files, and the `family.fea` files. I'll take it from there.

**Comment by twse** [comment]
This character is already added to the latest release from 16-Sep-2015. Maybe we can close this bug...

**Comment by molefunk** [comment]
On closer inspection it is actually just missing in the italic subset. Which, incidentally, is where we use it the most. I tried to learn how the font creation system worked, but it was a bit difficult to understand. Should I update the description of this issue?

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084. These are now present.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
