### ISSUE TITLE
package.json for binary releases

### ISSUE THREAD

**Issue by rarila** [adobe-fonts/source-sans-pro#82]
Would it be possible to add a ``package.json`` to the binary builds? Even better would be to have them officially registered with https://www.npmjs.com.
Thanks for the great font!

**Comment by miguelsousa** [comment]
That file is not necessary. Just run the command `npm install --fetch-only git://github.com/adobe-fonts/source-sans-pro.git#release`. This is listed in the install instructions.

**Comment by rarila** [comment]
Of course I read the instructions and tried that command, but if it ever worked, it does not work anymore (npm v3.5.0). I don't know if this is connected to the ``--fetch-only`` option as I can't find anywhere (Google, npm manual, npm help) information about it. I even searched the npm sources, but it doesn't seem to exist.

Executing ``npm install --fetch-only git://github.com/adobe-fonts/source-sans-pro.git#2.020R-ro/1.075R-it`` ends with ``EISDIR: illegal operation on a directory, read`` which seems to translate to [package.json is missing](https://github.com/npm/npm/issues/7232#issuecomment-71925514).

Also the npm FAQ as well as the npm install manual [indicates](https://docs.npmjs.com/misc/faq#what-is-a-package) that a package.json is mandatory.

**Comment by miguelsousa** [comment]
Well, `--fetch-only` works fine with version 2.14.3, which is what I had installed. I updated npm to v3.5.0 and running the command without `--fetch-only` works. You will see a few warnings in the console, but the files will download just fine. I'll update the install instructions for v3.x.

**Comment by bobdenotter** [comment]
I'm seeing the same behaviour on npm 2.14 as well as 3.5.2.. 

```
[bob:~]$ npm install git://github.com/adobe-fonts/source-sans-pro.git#2.020R-ro/1.075R-it
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! addLocal Could not install /var/folders/gv/sx6hdqk92ns99dmpwdq96_kh0000gn/T/npm-38955-63779860/git-cache-75986ad5/778e10a3656a899e0bc9f8a54d50a1ab4ba55308
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "git://github.com/adobe-fonts/source-sans-pro.git#2.020R-ro/1.075R-it"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bobdenotter/npm-debug.log
```

**Comment by rarila** [comment]
@bobdenotter The misunderstanding here is that – as I found out now – you have to see ``release`` literally and not as a placeholder to be replaced with a release tag as ``2.020R-ro/1.075R-it``.

Still I have problems on here (Windows 7, node v5.1.1, npm  v3.5.0), as it seems the fonts are generated in the temp folder but npm isn't able to copy them:

```npm WARN checkPermissions Missing write access to C:\…\node_modules\source-sans-pro```

Probably a Windows problem. Further investigating…

**Comment by miguelsousa** [comment]
@bobdenotter use the branch name `release` instead of the tag `2.020R-ro/1.075R-it`. The tag contains a slash character, and that's what's causing the problem.
