### ISSUE TITLE
COMBINING GRAPHEME JOINER' (U+034F) is Missing

### ISSUE THREAD

**Issue by embats** [adobe-fonts/source-sans-pro#83]
You can write the Name Citroën in two different ways in Unicode, using a Diaresis or an Umlaut:
To represent the umlaut use Combining Diaeresis (U+0308)
To represent the diaeresis use Combining Grapheme Joiner (CGJ, U+034F) + Combining Diaeresis (U+0308)

![bildschirmfoto 2015-12-08 um 15 56 39](https://cloud.githubusercontent.com/assets/1009797/11658784/dfeb421c-9dc4-11e5-84f1-245e2886b735.png)

In most Systemfonts this looks pretty nice, but in the Source-Sans-Pro Webfonts the U+034F is missing and you see some unexpected effects on some Browsers.

**Comment by pauldhunt** [comment]
Will put on my list for the next update.

**Comment by pauldhunt** [comment]
@embats can you give me more information as to which environments expect this character for proper display?

**Comment by erniemarch** [comment]
Checked in Roman version 2.034 and Italic version 1.084. This is now present.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
