### ISSUE TITLE
Small outline problem in Kadescender.a

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-sans-pro#84]
![screen shot 2016-01-19 at 17 33 31](https://cloud.githubusercontent.com/assets/2049645/12437446/d80b9dec-bed2-11e5-819a-f393f7d7a2cd.png)

**Comment by pauldhunt** [comment]
I think that I will actually remove these (curly) forms from the font.

**Comment by frankrolf** [comment]
👍
