### ISSUE TITLE
Lack of glyph "ō" (for Edge Web Fonts)

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-sans-pro#86]
N.B.: I only met this issue with the version hosted on Adobe Edge Web Fonts, while I hadn't tested the TypeKit version.
![satoo](https://cloud.githubusercontent.com/assets/3164826/13454907/6718169a-e017-11e5-801a-e441f41a2778.png)

**Comment by pauldhunt** [comment]
The reason that the o macron character is missing has to do with the subsetting options of the font server you are using, and not a deficiency in the font.

**Comment by ShikiSuen** [comment]
Thus could you plz tell me why the o macron is successfully displayed by Source Serif Pro in my screenshot?

**Comment by pauldhunt** [comment]
I’ll look more closely into this issue.

**Comment by fitojb** [comment]
> Thus could you plz tell me why the o macron is successfully displayed by Source Serif Pro in my screenshot?

One possibility could be: if you’ve installed Source Serif Pro locally, your browser will pick it up and render websites with that local copy, instead of downloading it from the web. I’ve seen many times that people are confused by this, as issues like this one arise.

**Comment by miguelsousa** [comment]
@ShikiSuen This is just a UI issue. Adobe Edge Web Fonts is serving the latest version of the fonts (v2.020), and they support the *ō*. To get the *ō* to display on your website, you'll have to select the *All characters* option.

<img width="298" alt="screen shot 2016-03-03 at 23 55 28" src="https://cloud.githubusercontent.com/assets/2119742/13521319/71700324-e19c-11e5-916d-19e7547e2825.png">
