### ISSUE TITLE
Cyrillic Support for Italics

### ISSUE THREAD

**Issue by Njke** [adobe-fonts/source-sans-pro#87]
Are there any plans on extending support for Cyrillic to Italics in Source Sans?

**Comment by miguelsousa** [comment]
Yes, there are plans for that. But it's too early to say when the new fonts will be available.

**Comment by Njke** [comment]
No problem, that is already a good news! Good luck! :+1:

**Comment by VladShcherbin** [comment]
Any news about the italics font?

Source Sans Pro is one of the best fonts, it would be awesome to have italics and to be able to use it from Google Fonts.

**Comment by pauldhunt** [comment]
Currently this aspect of the project is on my back burner, but I hope to bring it back to the fore within the next year. I apologize for the delay, I am currently swamped with other, more pressing projects.

**Comment by m4j** [comment]
Any news on that? Thanks

**Comment by pauldhunt** [comment]
I hope to be able to get to this later in the year. Other projects are currently taking priority.

**Comment by foodgy** [comment]
Are there any plans to add Cyrillic Light (300) and Cyrillic Light Italic as well?

**Comment by msklvsk** [comment]
I think the bigger problem is that it has _some_ Cyrillic glyphs. This makes Safari use Source Sans, leading to gaps.

## Google Chrome fallbacks the next font in CSS (here: Arial):

<img width="549" alt="image" src="https://user-images.githubusercontent.com/473012/47947667-7be41b00-df29-11e8-8a1a-22335130acd6.png">

## While Safari has gaps!
<img width="633" alt="image" src="https://user-images.githubusercontent.com/473012/47947676-9918e980-df29-11e8-86bb-e7491ac76467.png">

the page: [Universal Dependencies docs](http://universaldependencies.org/contributing.html#style-guidelines)

**Comment by pauldhunt** [comment]
This is my main priority for the next release of Source Sans.

**Comment by vrubleg** [comment]
When it is planned to be released?

**Comment by vrubleg** [comment]
@pauldhunt could you please provide a beta build, so we would be able to test it before the release, just to catch all possible issues if there are any?

**Comment by erniemarch** [comment]
confirm support in 3.006.

**Comment by vrubleg** [comment]
Thank you very much for the new release.

**Comment by davidschwegler** [comment]
It doesn't appear this is supported by Google Fonts yet. Is there anything we can do to get this fixed version up there?
https://fonts.google.com/specimen/Source+Sans+Pro

**Comment by fitojb** [comment]
@davidschwegler See https://github.com/google/fonts/issues/1744; nothing you can do but wait patiently.

**Comment by davidschwegler** [comment]
But it looks like that issue has been open 12 months?
