### ISSUE TITLE
Missing glyphs in Vietnamese subset

### ISSUE THREAD

**Issue by jameswilson** [adobe-fonts/source-sans-pro#90]
On Google Fonts there are a number of missing Vietnamese characters.

Some of the glyphs I've identified so far: (non-exhaustive list)

```
ậ ả ằ ầ ấ ể ệ ỉ ồ ớ ộ ủ ự  
```

Here is a pen that shows isolated snippets from the source text where the original problem was identified. I'm using a fallback to serif so you can clearly see which glyphs are missing. 

http://codepen.io/jameswilson/full/ZWgMaa/

What is particularly interesting in this example, is you can see that in some cases the two preceding letters before a special missing letter containing diacritics are also using the serif font. Really have no clue why that is happening.

<img width="388" alt="missing-glyphs-affect-preceding-glyphs" src="https://cloud.githubusercontent.com/assets/243532/15491361/4cd016c0-2135-11e6-9e29-5e02415dd91d.png">

This was originally reported to us by the TripAdvisor translation team, with respect to this page:

https://www.tripadvisor.com.vn/TripAdvisorInsights/n2623/danh-gia-nhanh-khao-sat-rieng-huong-dan-bat-dau-nhanh

They also reported a separate (but maybe related) issue where some browsers are rendering the diacritics way up too high.

Firefox:
<img width="708" alt="firefox" src="https://cloud.githubusercontent.com/assets/243532/15491257/48e1ade0-2134-11e6-80e9-24e2c8099622.png">

Safari:
<img width="699" alt="safari" src="https://cloud.githubusercontent.com/assets/243532/15491261/4cf0f328-2134-11e6-93b3-f88b14a66dad.png">

Hoping you might be able to shed some light on these two issues @pauldhunt ? I'm curious if this is a Google Fonts problem, i.e., these characters are implemented in recent versions of Source Sans Pro and just haven't been pushed up to Google's servers, or if they're also still missing in the master branch here on GitHub.

**Comment by pauldhunt** [comment]
James,

Unfortunately I know nothing of Google��s subsetting scheme. I do know that all the requisite glyphs for Vietnamese are included in the fonts, however. To remedy this situation you might consider self-hosting the fonts on your site or perhaps using the Typekit service. Please let me know if you have additional questions on the fonts, but I cannot give you more information about how Google��s services work.

**Comment by jameswilson** [comment]
Thanks Paul.  We're already self hosting custom compiles for Cyrillic and Greek.  I suppose we'll need to do the same for Vietnamese.

**Comment by adrientetar** [comment]
cc @davelab6

**Comment by davelab6** [comment]
Thanks for reporting this @jameswilson and @adrientetar for the heads up.

**Comment by davelab6** [comment]
@miguelsousa you can probably close this as really it should be reported on google/fonts

**Comment by jameswilson** [comment]
For the record, in case someone else finds this helpful, I ended up self-hosting, and had to figure out how to create my own subset for Vietnamese.  I used font-squirrel's webfont generator, uploading the Source Sans Pro TTF files of various weights, and specifying on the "Advanced" tab the following unicode ranges for the glyph sets:

    0020-002F,0030-0039,003A-0040,0041-005A,005B-0060,0061-007A,007B-007E,00C0-00C3,00C8-00CA,00CC-00CD,00D0,00D2-00D5,00D9-00DA,00DD,00E0-00E3,00E8-00EA,00EC-00ED,00F2-00F5,00F9-00FA,00FD,0102-0103,0110-0111,0128-0129,0168-0169,01A0-01B0,1EA0-1EF9,02C6-0323

In addition to those ranges, I enabled various other checkboxes on the "Advanced" settings, such as numbers, and mathematical characters.
