### ISSUE TITLE
non-standard final glyph names for fi & fl ligatures

### ISSUE THREAD

**Issue by pauldhunt** [adobe-fonts/source-sans-pro#91]
The final names should be f_i and f_l, respectively.

**Comment by miguelsousa** [comment]
`fi` and `fl` are standard names, as they're part of the [MacRoman](https://en.wikipedia.org/wiki/Mac_OS_Roman) character set and are also listed in the [AGL](https://github.com/adobe-type-tools/agl-aglfn/blob/master/glyphlist.txt#L1873).

But it's fine to change these names and make them consistent with the other ligatures.
