### ISSUE TITLE
Missing Metadata on Windows 7+ Control Panel

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-sans-pro#92]
I am using official TTF build with digital signature, but the “Designed For”, “Category” and “Manufacturer” field is missing.

![image](https://cloud.githubusercontent.com/assets/240091/15983606/210b1648-2fe0-11e6-9257-5a3453312372.png)

Same problem on adobe-fonts/source-code-pro#129

**Comment by miguelsousa** [comment]
See https://github.com/adobe-fonts/source-code-pro/issues/129#issuecomment-225342644
