### ISSUE TITLE
Crossed seven alternate glyph

### ISSUE THREAD

**Issue by lfourquaux** [adobe-fonts/source-sans-pro#93]
It would be nice to include a crossed 7 glyph (i.e. with a short horizontal bar in the middle, see
https://en.wikipedia.org/wiki/Arabic_numeral_variations#Other_variations
if you don't know what it is) as an OpenType stylistic set.
This is a very common variant of the glyph in Europe, although few computer fonts have it.  Like the slashed (or dotted) zero, the point of the extra bar is to avoid ambiguities.

**Comment by frankrolf** [comment]
I politely disagree –this is a feature of handwriting, almost never found in printed type (not only computer fonts). It feels out of place especially in a sans serif design, and fits only very idiosyncratic typefaces, such as Schadow. 
Disclaimer: I am European.

**Comment by pauldhunt** [comment]
Are you European? Or are you German?

?

Sent from my iPhone

On 12 Jun 2016, at 4:38 AM, Frank Grie?hammer <notifications@github.com<mailto:notifications@github.com>> wrote:


I politely disagree -this is a feature of handwriting, almost never found in printed type (not only computer fonts). It feels out of place especially in a sans serif design, and fits only very idiosyncratic typefaces, such as Schadow.
Disclaimer: I am European.

-

**Comment by twse** [comment]
The UVN fonts designed for use with the Vietnamese language (downloadable from the TTI site), have a crossed seven for the number itself.

**Comment by pauldhunt** [comment]
I have seen this form in handwriting, but rarely in fonts. I find the form too idiosyncratic to include in SSP, which is meant to be very middle-of-the-road in terms of design.
