### ISSUE TITLE
Support for small caps ampersand?

### ISSUE THREAD

**Issue by simonjbeaumont** [adobe-fonts/source-sans-pro#94]
Perhaps I am mistaken but it seems that there is no support for small caps ampersand and so it juts above the rest of the small caps:

<img width="339" alt="screen shot 2016-07-10 at 19 30 02" src="https://cloud.githubusercontent.com/assets/1125539/16715339/bb23b892-46d4-11e6-9f37-107873da13d2.png">

Numerals seem to be supported...

<img width="452" alt="screen shot 2016-07-10 at 19 31 43" src="https://cloud.githubusercontent.com/assets/1125539/16715346/f585843e-46d4-11e6-88db-94abee8e8478.png">

**Comment by miguelsousa** [comment]
You need to apply the `c2sc` (Small Capitals From Capitals) feature to get the small cap ampersand.

**Comment by simonjbeaumont** [comment]
That's great. Thanks for the pointer. Thought I must have been missing something.
