### ISSUE TITLE
Add common MAC OS specific glyphs

### ISSUE THREAD

**Issue by Harkko** [adobe-fonts/source-sans-pro#97]
Would be good to add common MAC OS / OS X specific glyphs to the font, as the font is designed to be used with UI's. Many UI's usually show these glyphs next to the menu options / commands noting the equivalent keyboard shortcuts to be trigger these commands. For example, [Slack](https://slack.com/) web and OS X app UI:
<img width="312" alt="screen shot 2016-07-18 at 13 52 47" src="https://cloud.githubusercontent.com/assets/9257640/16912773/da235d36-4cee-11e6-85f6-81e79fb997e1.png">

In my opinion, at least the "Command", "Option" and "Delete" -key symbols should be added to Source Sans Pro:
- **⌘**, U+2318,  "Command" or "Place of Interest Sign"
- **⌥**,  U+2325, "Option Key" or "Alt"
- **⌫**, U+232B, "Remove" (/Delete) or "Erase to the Left"

**Comment by pauldhunt** [comment]
would you like to submit a pull request with these?

**Comment by Harkko** [comment]
@pauldhunt Sure! In which formats do you need the font files? Is `.otf `(OpenType) enough? Also: will my contribution only be valid if I make the characters for **Regular** and **Semibold** weights? Source Sans has a lot of weights and it's a lot of work to make the equivalent weights for ALL of them…

**Comment by Harkko** [comment]
@pauldhunt Currently I would have time to only push the **Regular**-weight versions of these five glyphs:
- ⌘, U+2318, "Command" or "Place of Interest Sign"
- ⌥, U+2325, "Option Key" or "Alt"
- ⌫, U+232B, "Remove" (/Delete) or "Erase to the Left"
- ⇧, U+21E7, "Upwards White Arrow" or "Shift"
- ⌃, U+2303. "Up Arrowhead" or "Control"

Is it an OK commit to only include the .glif versions of these into the font? What else should be included in the commit for accepting this to be merged to the master?

Sorry, but I can't seem to find any instructions anywhere for the contributors of some glyphs…

**Comment by pauldhunt** [comment]
are these glyphs that you have designed? do you own the copyright to this material? Have you done the work already? If not, perhaps I can try to set you up with a template file (Ai? SVG?) file and you can submit outlines that way.

**Comment by Harkko** [comment]
@pauldhunt That sounds **great** Paul! Please hook me up :) my gmail is hannu.aarniala.

**Comment by pauldhunt** [comment]
What format would you prefer?

**Comment by Harkko** [comment]
Sorry about the delay! Was on holiday…

I'm probably doing the glyphs it with .ai, but SVG is also ok!

Thanks,

**Comment by pauldhunt** [comment]
These actually look fairly simple. I will add them to my list of items for the next release.

**Comment by Harkko** [comment]
Ok @pauldhunt ! Sounds good! Do you still know when the release is due?

**Comment by Harkko** [comment]
And, sorry, but you mean to add all of these 5 symbols?

> ⌘, U+2318, "Command" or "Place of Interest Sign"
⌥, U+2325, "Option Key" or "Alt"
⌫, U+232B, "Remove" (/Delete) or "Erase to the Left"
⇧, U+21E7, "Upwards White Arrow" or "Shift"
⌃, U+2303, "Up Arrowhead" or "Control"

**Comment by pauldhunt** [comment]
There is no release currently scheduled, but there are some changes on my radar that I hope to get pushed out within the next year or so, including adding the Greek & Cyrillic italics.

**Comment by Harkko** [comment]
@pauldhunt I see. If it's ok to you, I could still try produce these quickly? It might be that our devs want me to fix this PR related to our product within the next 3 months or so.

I don't want to push you, so if the release is not due anytime soon, I could try push these glyphs to the regular and semibold weights? As I might still have to produce them in this quarter to be included in our product.

So, If you could send me the .ai-template for the glyphs, it would help a lot :)

**Comment by pauldhunt** [comment]
what styles do you need?

**Comment by Harkko** [comment]
@pauldhunt Regular and Semibold would be enough for now, thanks!

**Comment by pauldhunt** [comment]
@Harkko did you get my email?

**Comment by Harkko** [comment]
Sorry, no :(

Could you try again to my gmail address? it's my name – Hannu Aarniala (dot seperated) – at gmail etc.

**Comment by Harkko** [comment]
@pauldhunt If it's not too much trouble, could you give me an estimate when this issue would be fixed? I'm asking because this issue is in our products' backlog and becoming more and more noticed by the users (e.g. not having these next to commands in the File -menus)

Or if it's possible, if you could send me ai.-templates mentioned before? I might have to try to build the font with after adding these to it myself.

**Comment by LilianValero** [comment]
Hi @pauldhunt @miguelsousa, where can I find:
- SourceSansPro-Regular.ttf/SourceSansPro-Bold.ttf/SourceSansPro-SemiBold.ttf
- SourceSansPro-Regular.eot
- SourceSansPro-Regular.woff
containing these MacOS glyphs, please?
TIA

**Comment by miguelsousa** [comment]
@LilianValero there are no font builds yet that contain these glyphs.

**Comment by LilianValero** [comment]
@miguelsousa may they be included in the master branch ?

**Comment by miguelsousa** [comment]
> may they be included in the master branch ?

What, the fonts? No, they will be committed to the `release` branch when they're done. Right now the glyphs only exist in the master UFOs of the `PaulFix` branch.

**Comment by LilianValero** [comment]
Ok Thks. How can I be informed when the glyphs will be available in one public branch?

**Comment by miguelsousa** [comment]
@LilianValero just subscribe to the repository, and you should get a notification when we issue a new release.

**Comment by LilianValero** [comment]
Ok Thks. Let's do that.

**Comment by miguelsousa** [comment]
Fixed in version 2.040.
