### ISSUE TITLE
Generating font files that use a stylistic alternate as the default glyph

### ISSUE THREAD

**Issue by filipjakobsen** [adobe-fonts/source-sans-pro#98]
Due to the non-universal support for stylistic alternates in web type, I'd like to package a version of the font with a stylistic set as the default; using the alternate lowercase L glyph as the standard for lowercase Ls. Packaging a font where it is the standard glyph would enable me to get the proper glyphs shown even on browsers that do not support the necessary font-feature properties that can be set in CSS. How can I achieve this — generating a new family of fonts that simply use the alternate lowercase L as the default one?

Thank you,

**Comment by Manuel-K** [comment]
The easiest way that I know is the open type flattening option available in the expert mode of https://www.fontsquirrel.com/tools/webfont-generator. You can use it to generate custom ttf files.

**Comment by khaledhosny** [comment]
Out of curiosity, what browsers don’t support font features these days?

**Comment by filipjakobsen** [comment]
@Manuel-K Thanks – I just tried that. It returns this message: "Adobe has requested that their font Source Sans Pro Semibold Regular be blacklisted by the Generator. You will not be able to convert this font."
@khaledhosny Judging from http://stateofwebtype.com/#stylistic the support unfortunately does not seem to be complete across browsers

**Comment by khaledhosny** [comment]
One can always fallback to `font-feature-settings` which seems to be nearly universally supported http://caniuse.com/#feat=font-feature.

**Comment by filipjakobsen** [comment]
@khaledhosny One would think so. As I understand it, http://stateofwebtype.com/ breaks down e.g. font-feature into more granular properties to indicate if browsers have full support of all potential uses of a property. If I compare the version numbers on http://stateofwebtype.com/#stylistic and the version numbers on http://caniuse.com/#feat=font-feature, there seems to be some discrepancies. Since stateofwebtype's analysis is more granular (but still include modern version numbers of the different browsers), I would assume them to be the more reliable source. Font-feature would be the easiest, but since it seems that it does not have full support across browsers, I am looking for a more versatile method; The only fully reliable solution, as I understand it, (and without requiring javascript or something similar to make it work), would be generating some font files that just have the alternate style preference for certain letters turned on by default, without any properties having to be set in CSS.

**Comment by moyogo** [comment]
@filipjakobsen https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze is an option for you.

**Comment by miguelsousa** [comment]
> I just tried that. It returns this message: "Adobe has requested that their font Source Sans Pro Semibold Regular be blacklisted by the Generator. You will not be able to convert this font."

@filipjakobsen it works for me. Are you using the [latest version](https://github.com/adobe-fonts/source-sans-pro/releases/latest) for the font?

**Comment by filipjakobsen** [comment]
@miguelsousa I tried with the latest version of the fonts and that seems to work. Thanks for the tip!
@moyogo Thanks! I will try out FontSquirrel and if I run into issues with that I will try out the tool you suggest.
